
// ======================================================
// SECTION:GLOBALS
// ======================================================

// Reset daily use items and timers to 0 because when first AI first turned on the timer's 
// value is unintialized and can be large.
IF
    PartyRested()
THEN
    RESPONSE #100
        SetGlobal("USED_RING33","LOCALS",0)
        SetGlobal("USED_STAF21","LOCALS",0)
        SetGlobal("USED_SW1H26","LOCALS",0)
        SetGlobal("USED_clck08","LOCALS",0)
        SetGlobal("USED_BOOT12","LOCALS",0)
        SetGlobal("USED_ohbrew06","LOCALS",0)
        SetGlobalTimer("FIRE_ENEMIES","LOCALS",0)
        SetGlobalTimer("CASTER_ENEMY","LOCALS",0)
        SetGlobalTimer("TROLL_ENEMIES","LOCALS",0)
        SetGlobalTimer("USE_RANGE","LOCALS",0)
        SetGlobalTimer("PSYCHIC_ENEMIES","LOCALS",0)
        Continue()
END

// Set a timer for short-duration buffs
// This section sets a global timer to track the duration of short-duration buffs.
// The timer is set to two rounds initially and updated to one round when a hotkey is pressed.
IF
    ActuallyInCombat()
    ActionListEmpty()
    Delay(12)
THEN
    RESPONSE #100
        SetGlobalTimer("SHORT_BUFF","LOCALS",FIVE_ROUNDS)
        Continue()
END

// This section sets a global timer for casting area-of-effect spells if there are more than 3 enemies nearby.
IF
    Delay(12)
    OR(5)
        ActuallyInCombat()
        Exists([ENEMY])
        AreaCheck("OH8200")
        AreaCheck("OH8300")
        AreaCheck("OH8400")
THEN
    RESPONSE #100
        SetGlobalTimer("SUMMON","LOCALS",FIVE_ROUNDS)
        Continue()
END

IF
    HotKey(K)  // Detect pressing of the 'B' key
THEN
    RESPONSE #100
        SetGlobalTimer("SUMMON","LOCALS",FIVE_ROUNDS)  // Set the timer to one round
        Continue()
END

IF
    HotKey(B)  // Detect pressing of the 'B' key
THEN
    RESPONSE #100
        SetGlobalTimer("SHORT_BUFF","LOCALS",ONE_TURN)  // Set the timer to one round
        Continue()
END


// ======================================================
// SECTION: Area Check
// ======================================================

//If I'm in the blackpits area, I cannot cast buffs/spells so just continue.
IF
    ActionListEmpty()
    AreaCheck("OH8100")
THEN
    RESPONSE #100
        Continue()
        Wait(10)
END

// ======================================================
// SECTION: ENEMY DETECTION
// ======================================================

/*
This section of the code is for determining which enemy is currently being faced. 
For each enemy type:
    set timer for enemy type

    Subsequent logic blocks will check these timers in conjuction or individually
    taking the resulting intelligent actions. 

    Example: facing fire elementals, do not use fire spells, 
    do cast fire protection spells if my resistance is low, 
    buff allies for fire protection if they are low. 
    Use specific items like charm fire elemental if the elemental is evil. 
*/


// See Fire Type Elemental with high resistance, don't use fire spells.
// General form [EA.GENERAL.RACE.CLASS.SPECIFIC.GENDER.ALIGN].
IF
    ActionListEmpty()
    Delay(30)
    OR(9)
        Detect([ENEMY.0.0.ELEMENTAL_FIRE.0])
        Detect([ENEMY.0.0.GREY_OOZE])
        Class(NearestEnemyOfType,MAGE_ALL)
        Class(NearestEnemyOfType,SORCERER)
        Class(NearestEnemyOfType,DRUID_ALL)
        Class(NearestEnemyOfType,CLERIC_ALL)
        Class(NearestEnemyOfType,ELEMENTAL_FIRE)
        Class(NearestEnemyOfType,RED_DRAGON)
        Class(NearestEnemyOfType,SILVER_DRAGON)
    !GlobalTimerNotExpired("FIRE_ENEMIES","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("FIRE_ENEMIES","LOCALS",ONE_MINUTE)
        Continue()
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    Delay(30)
    OR(8)
        See(NearestEnemyOfType([ENEMY.0.0.MAGE_ALL]))
        See(NearestEnemyOfType([ENEMY.0.0.CLERIC_ALL]))
        See(NearestEnemyOfType([ENEMY.0.0.BARD_ALL]))
        See(NearestEnemyOfType([ENEMY.0.0.DRUID_ALL]))
        See(NearestEnemyOfType([ENEMY.0.0.SORCERER]))
        See(NearestEnemyOfType([ENEMY.0.0.RAKSHASA]))
        See(NearestEnemyOfType([ENEMY.0.LICH]))
        See(NearestEnemyOfType([ENEMY.0.DEMILICH]))
    GlobalTimerExpired("CASTER_ENEMY","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("CASTER_ENEMY","LOCALS",ONE_TURN)
        Continue()
END

// Detect Troll-type enemies, prepare to use anti-Troll strategies.
IF
    ActionListEmpty()
    Delay(30)
    Detect([ENEMY.0.0.TROLL.0])
    !GlobalTimerNotExpired("TROLL_ENEMIES","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("TROLL_ENEMIES","LOCALS",ONE_TURN)
        Continue()
END

IF
    ActionListEmpty()
    Delay(30)
    Detect([ENEMY.0.0.GREEN_SLIME])
    !GlobalTimerNotExpired("SLIME_ENEMIES","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("SLIME_ENEMIES","LOCALS",ONE_TURN)
        Continue()
END

IF
    ActionListEmpty()
    OR(2)
        Detect([ENEMY.0.0.UMBERHULK.0])
        Detect([ENEMY.0.0.MIND_FLAYER.0])
        Detect([ENEMY.0.0.MIND_FLAYER.0])
        Detect([ENEMY.0.0.MIND_FLAYER.0])
    !GlobalTimerNotExpired("PSYCHIC_ENEMIES","LOCALS")
    Delay(30)
THEN
    RESPONSE #100
        SetGlobalTimer("PSYCHIC_ENEMIES","LOCALS",ONE_TURN)
        Continue()
END


// ======================================================
// SECTION: CHECK FOR CROWD CONTROLLED PARTY MEMBERS To USE RANGE
// ======================================================

// Check for crowd-controlled party members
// This section randomly walks if any party member is affected by crowd control spells or if the wizard is helpless.
IF
    ActionListEmpty()
    ActuallyInCombat()
    CheckStatLT(Myself,1,CLERIC_FREE_ACTION) // Check if party is being crowd-controlled
    CheckStatLT(Myself,1,MINORGLOBE)
    CheckStatLT(Myself,1,SHIELDGLOBE)
    OR(8)
        CheckStat([ANYONE],1,WEB)
        CheckStat([ANYONE],1,GREASE)
        CheckSpellState([ANYONE],PRONE)
        SpellCast([ANYONE],WIZARD_WEB)  // SPWI215.SPL (Web)
        SpellCast([ANYONE],WIZARD_DEATH_FOG)
        SpellCast([ANYONE.0.0.0],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
        SpellCast([ANYONE.0.0.0],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
        SpellCast([ANYONE.0.0.0],WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
        SpellCast([ANYONE.0.0.0],WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
        SpellCast([ANYONE.0.0.0],WIZARD_ABI_DALZIMS_HORRID_WILTING)
    Range([ANYONE],13)
    Delay(18)
THEN
    RESPONSE #100
        SetGlobalTimer("USE_RANGE","LOCALS",FIVE_ROUNDS)
        SetInterrupt(FALSE)
        RunAwayFromNoInterruptNoLeaveArea([ANYONE],90)
        SetInterrupt(TRUE)
END

//If I'm in combat, and not near an ally go to them. Note, we can't evaluate this to attack nearest because we need to see what is nearest the player...
IF
    ActionListEmpty()
    CheckStatLT(Myself,1,CLERIC_FREE_ACTION) // Check if party is being crowd-controlled
    CheckStatLT(Myself,1,MINORGLOBE)
    CheckStatLT(Myself,1,SHIELDGLOBE)
    OR(1)
        SpellCastOnMe([ANYONE],WIZARD_WEB)
  THEN
    RESPONSE #100
        //Global Shout Alert, then run away from anyone else
        GlobalShout(125)
        SetGlobalTimer("USE_RANGE","LOCALS",FIVE_ROUNDS)
        RunAwayFromNoInterrupt([PC],60) 
        Continue()
END


IF
    ActionListEmpty()
    Heard([PC],ALERT)
    Range(LastHeardBy(Myself),30)
  THEN
    RESPONSE #100
        SetGlobalTimer("USE_RANGE","LOCALS",FIVE_ROUNDS)
        RunAwayFromNoInterrupt(LastHeardBy(Myself),60)
END

// Cast Zone of Sweet Air if affected by Stinking Cloud
// This section casts Zone of Sweet Air if the wizard or party members are affected by Stinking Cloud.
IF
    ActionListEmpty()
    OR(5)
        SpellCast([ENEMY.0.0.0],WIZARD_INCENDIARY_CLOUD)  
        SpellCast([ENEMY.0.0.0],WIZARD_STINKING_CLOUD)  
        SpellCast([ENEMY.0.0.0],WIZARD_CLOUDKILL) 
        SpellCast([ENEMY.0.0.0],WIZARD_DEATH_FOG) 
        SpellCast([ENEMY.0.0.0],WIZARD_ABI_DALZIMS_HORRID_WILTING) 

    HaveSpell(CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_ZONE_OF_SWEET_AIR)  // Cast Zone of Sweet Air to counteract Stinking Cloud
END

// ======================================================
// SECTION: IMMUNITIES (WIZARD)
// ======================================================

/*
Protection From Magical Weapons
(Abjuration)

Level: 6
Range: 0
Duration: 4 rounds
Casting Time: 1
Area of Effect: The caster
Saving Throw: None 

When the spell is cast, it confers complete invulnerability to all magical weapons. 
This includes weapons that are blessed or enchanted. 
The attacks of powerful monsters are also considered magical weapons. 
This spell cannot be cast on anyone who is protected from normal weapons as well as anyone protected by 
Mantle, Improved Mantle, or Absolute Immunity. Due to the nature of this spell, with the short casting time and duration, 
it is mainly used to buy the wizard a few rounds in the thick of combat. 
This effect lasts for the duration of the spell or until dispelled.
*/
IF
    ActionListEmpty()
    HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    TookDamage()
    !CheckSpellState(Myself,PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


/*
Protection From Magic Energy
(Abjuration)

Level: 6
Range: Touch
Duration: 1 turn/level
Casting Time: 6
Area of Effect: 1 creature
Saving Throw: None

When the spell is cast, it confers 100% invulnerability to all 
magic-based attacks such as Magic Missile or Abi-Dalzim's Horrid Wilting.
This effect lasts for the duration of the spell or until dispelled.
*/
IF
    ActionListEmpty()
    HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
    OR(6)
        HitBy([ANYONE],ACID)
        HitBy([ANYONE],COLD)
        HitBy([ANYONE],ELECTRICITY)
        HitBy([ANYONE],FIRE)
    !CheckStat(Myself,1,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

// ======================================================
// SECTION: RETREAT CONDITION
// ======================================================


IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    Range(LastSeenBy(Myself),15)
    AttackedBy([ENEMY],DEFAULT)
    HPPercentLT(Myself,60)
    HaveSpell(WIZARD_SHADOW_DOOR)
THEN
    RESPONSE #100
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        FaceObject(LastSeenBy(Myself))
        Spell(Myself,WIZARD_SHADOW_DOOR)  // SPWI505.SPL (Shadow Door)
        SetInterrupt(FALSE)
        RunAwayFromNoInterruptNoLeaveArea([ANYONE],60)
        SetInterrupt(TRUE)
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    Range(LastSeenBy(Myself),10)
    AttackedBy([ENEMY],DEFAULT)
    HPPercentLT(Myself,80)
    HaveSpell(WIZARD_MISLEAD)
THEN
    RESPONSE #100
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        FaceObject(LastSeenBy(Myself))
        Spell(Myself,WIZARD_MISLEAD)  // SPWI505.SPL (Shadow Door)
        SetInterrupt(FALSE)
        RunAwayFromNoInterruptNoLeaveArea([ANYONE],60)
        SetInterrupt(TRUE)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HPPercentLT(Myself,60)
    AttackedBy([ENEMY],DEFAULT)
    !StateCheck(Myself,STATE_INVISIBLE)
    HaveSpell(WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_INVISIBILITY)  // Turn invisible to retreat
        RunAwayFrom(NearestEnemyOf(Myself),30)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    Delay(18)
    OR(3)
        Class(Myself,THIEF_ALL)
        Class(Myself,MONK)
        Class(Myself,BARD_ALL)
    !StateCheck(Myself,STATE_INVISIBLE)
    !GlobalTimerNotExpired("USE_RANGE","LOCALS")
THEN
    RESPONSE #100
        RunAwayFrom(NearestEnemyOf(Myself),30)
        Hide()
        EquipMostDamagingMelee()
        AttackOneRound(NearestEnemyOf(Myself))
END


IF
    ActionListEmpty()
    ActuallyInCombat()
    AttackedBy([ENEMY],MELEE)
    Exists(LastAttackerOf(Myself))
    OR(3)
        Class(Myself,MAGE)
        Class(Myself,THIEF)
        Class(Myself,BARD)
    Delay(8)
    HPPercentLT(Myself,80)
THEN
    RESPONSE #100
        RunAwayFromNoLeaveArea(LastAttackerOf(Myself),30)
        Continue()
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    AttackedBy([ENEMY],DEFAULT)
    Exists(LastAttackerOf(Myself))
    Class(Myself,MAGE)
    Delay(10)
THEN
    RESPONSE #100
        RunAwayFromNoLeaveArea(LastAttackerOf(Myself),30)
        Continue()
END

// ======================================================
// SECTION: PRE-COMBAT BUFFING (WIZARD)
// ======================================================
// Cast Spirit Armor
// Casts Spirit Armor to provide a magical shield that improves the wizard's armor class.
// Lasts for 1 hour per caster level.
IF
    ActionListEmpty()
    HaveSpell(WIZARD_CONTINGENCY)  // SPWI414.SPL (Spirit Armor)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_CONTINGENCY)  // Cast Spirit Armor for increased defense
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(WIZARD_MINOR_SEQUENCER) 
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_MINOR_SEQUENCER) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END
// Cast Spirit Armor
// Casts Spirit Armor to provide a magical shield that improves the wizard's armor class.
// Lasts for 1 hour per caster level.
IF
    ActionListEmpty()
    HaveSpell(WIZARD_SPIRIT_ARMOR)  // SPWI414.SPL (Spirit Armor)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_SPIRIT_ARMOR)  // Cast Spirit Armor for increased defense
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

// Cast Stoneskin
// Casts Stoneskin to grant the wizard protection from physical damage by turning their skin to stone.
// Lasts for 1 turn per caster level.
IF
    ActionListEmpty()
    HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
    CheckStatLT(Myself,1,STONESKINS)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_STONE_SKIN)  // Cast Stoneskin for increased damage resistance
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

// Cast Ghost Armor
// Casts Ghost Armor to provide an ethereal shield that grants a bonus to armor class.
// Lasts for 1 round per caster level.
IF
    ActionListEmpty()
    HaveSpell(WIZARD_GHOST_ARMOR)  // SPWI317.SPL (Ghost Armor)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)  
    CheckStatLT(Myself,1,DEAD_MAGIC)   
    CheckStatGT(Myself,2,ARMORCLASS)   
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_GHOST_ARMOR)  // Cast Ghost Armor for improved defense
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

// Cast Armor
// Casts Armor to provide a magical armor that improves the wizard's armor class.
// Lasts for 1 hour per caster level.
IF
    ActionListEmpty()
    HaveSpell(WIZARD_ARMOR)  // SPWI102.SPL (Armor)
    CheckStatGT(Myself,6,ARMORCLASS)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_ARMOR)  // Cast Armor for increased protection before combat
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

// Cast Shield
// Casts Shield to provide a magical shield that improves the wizard's armor class and grants a +4 bonus to AC.
// Lasts for 1 turn per caster level.
IF
    ActionListEmpty()
    HaveSpell(WIZARD_SHIELD)  // SPWI114.SPL (Shield)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_SHIELD)  // Cast Shield for added protection
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

// Cast Protection from Normal Missiles
// Casts Protection from Normal Missiles to grant immunity to normal missile attacks.
// Lasts for 1 hour
IF
    ActionListEmpty()
    HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI107.SPL (Protection from Normal Missiles)
    OR(3)
        LevelLT([ENEMY],12)
        !ActuallyInCombat()
        HitBy([ENEMY],MISSILE)
    //Check if missiles are normal 
    OR(4)
        !ActuallyInCombat() 
        HasItemEquiped("BULL01",[ENEMY])
        HasItemEquiped("AROW01",[ENEMY])
        HasItemEquiped("BOLT01",[ENEMY])
    CheckStatLT(Myself,1,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // Check if Protection from Normal Missiles is already active
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // Cast Protection from Normal Missiles
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

// Cast Resist Fear
// Casts Resist Fear to grant the wizard immunity to fear effects.
// Lasts for 1 turn per caster level.
IF
    !ActuallyInCombat()
    ActionListEmpty()
    HaveSpell(WIZARD_RESIST_FEAR)  // SPWI103.SPL (Resist Fear)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")  // Ensure the spell is not recently cast
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_RESIST_FEAR)  // Cast Resist Fear for protection against fear
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END
// Cast Protection from Petrification
// Casts Protection from Petrification to grant immunity to petrification attacks.
// Lasts for 1 hour
IF
    ActionListEmpty()
    !ActuallyInCombat()
    HaveSpell(WIZARD_PROTECTION_FROM_PETRIFICATION)  // SPWI212.SPL (Protection from Petrification)
    CheckStatLT(Myself,1,WIZARD_PROTECTION_FROM_PETRIFICATION)  // Check if Protection from Petrification is already active
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)
    GlobalTimerExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_PROTECTION_FROM_PETRIFICATION)  // Cast Protection from Petrification
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

// ======================================================
// SECTION: PRE-COMBAT BUFFING (CLERIC)
// ======================================================


// ======================================================
// SECTION: Heal SPELLS (CLERIC)
// ======================================================


// Description: EXALTATION: This spell enables a priest to aid and protect any one being other than themselves. 
// By touch, the caster removes the effects of fear, sleep, feeblemind, unconsciousness, and intoxication, 
//as well as berserk and confused states of mind. In addition, the recipient is protected 
//against spells and other attacks that cause these effects for 1 turn.
IF
    ActionListEmpty()
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HaveSpellRES("OHTYR1") //Exaltation filename. 
    See([PC])
    OR(8)
        GlobalTimerNotExpired("CASTER_ENEMY","LOCALS")
        CheckStat(LastSeenBy(Myself),1,WEB)
        CheckStat(LastSeenBy(Myself),1,GREASE)
        StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
        StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
        StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
        StateCheck(LastSeenBy(Myself),STATE_PANIC)
        StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
THEN
    RESPONSE #100
        SpellRES("OHTYR1",LastSeenBy(Myself))
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HaveSpell(CLERIC_FREE_ACTION) //Exaltation filename. 
    See([PC])
    !CheckSpellState(LastSeenBy(Myself),FREE_ACTION)
    OR(3)
        CheckStat(LastSeenBy(Myself),1,WEB)
        CheckStat(LastSeenBy(Myself),1,GREASE)
        CheckSpellState(LastSeenBy(Myself),ENTANGLE)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_FREE_ACTION)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HaveSpell(CLERIC_FREE_ACTION) //Exaltation filename. 
    !CheckSpellState(Myself,FREE_ACTION)
    OR(3)
        CheckStat(LastSeenBy(Myself),1,WEB)
        CheckStat(LastSeenBy(Myself),1,GREASE)
        CheckSpellState(LastSeenBy(Myself),ENTANGLE)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_FREE_ACTION)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    OR(3)
        HPPercentLT(Myself,60) // Heal when HP is below 20
        StateCheck(Myself,STATE_DISEASED)
        CheckSpellState(Myself,NAUSEA)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HaveSpell(CLERIC_HEAL)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_HEAL)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND) // Set a 2-minute timer
END

IF
    ActionListEmpty()
    StateCheck([PC],STATE_POISONED)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HaveSpell(CLERIC_SLOW_POISON)
THEN
    RESPONSE #100
        Spell([PC],CLERIC_SLOW_POISON)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND) // Set a 2-minute timer
END

IF
    ActionListEmpty()
    See([PC])
    OR(3)
        HPPercentLT(LastSeenBy(Myself),60) // Heal when HP is below 20
        StateCheck(LastSeenBy(Myself),STATE_DISEASED)
        CheckSpellState(LastSeenBy(Myself),NAUSEA)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HaveSpell(CLERIC_HEAL)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_HEAL)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND) // Set a 2-minute timer
END

// Heal Light Wounds
IF
    ActionListEmpty()
    See([PC])
    HPPercentLT([PC],60) // Heal when HP is below 70
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HaveSpell(CLERIC_MASS_CURE)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_MASS_CURE)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND) // Set a 2-minute timer (adjust as needed)
END

IF
    ActionListEmpty()
    See([PC])
    HPPercentLT([PC],70) // Heal when HP is below 70
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND) // Set a 2-minute timer (adjust as needed)
END

// Heal Serious Wounds
IF
    ActionListEmpty()
    See([PC])
    HPPercentLT([PC],50) // Heal when HP is below 50%
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CURE_SERIOUS_WOUNDS)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND) // Set a 2-minute timer
END

IF
    ActionListEmpty()
    See([PC])
    HPPercentLT([PC],70) // Heal when HP is below 70%
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HaveSpell(CLERIC_AID)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_AID)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND) // Set a 2-minute timer (adjust as needed)
END

// Heal Light Wounds
IF
    ActionListEmpty()
    See([PC])
    HPPercentLT([PC],70) // Heal when HP is below 70
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

//Innate cure light wounds
IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpellRES("SPIN101")  
    HPPercentLT([PC],70) // Heal when HP is below 70%
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        SpellRES("SPIN101",[PC]) 
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END


IF
    ActionListEmpty()
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    OR(2)
        StateCheck([PC],STATE_STUNNED)
        CheckStatGT([PC],0,HELD)
    HaveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
        Spell([PC],CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
        SetInterrupt(TRUE)
END

IF
    ActionListEmpty()
    HaveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR303.SPL (Dispel Magic)
    OR(2)
        StateCheck([PC],STATE_CHARMED)
        StateCheck([PC],STATE_CONFUSED)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([PC],CLERIC_CHAOTIC_COMMANDS)  // SPPR303.SPL (Dispel Magic)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND) // Set a 2-minute timer
END

IF
    ActionListEmpty()
    HaveSpell(CLERIC_DISPEL_MAGIC)  
    See([PC])
    OR(4)
        StateCheck([PC],STATE_CHARMED)
        StateCheck([PC],STATE_CONFUSED)
        StateCheck([PC],STATE_STUNNED)
        CheckStatGT([PC],0,CLERIC_INSECT_PLAGUE)
        CheckStatGT([PC],0,HELD)
THEN
    RESPONSE #100
        Spell([PC],CLERIC_DISPEL_MAGIC)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND) 
END

IF
    HaveSpell(CLERIC_FREE_ACTION) 
    OR(3)
        CheckStatGT([PC],0,HELD)
        CheckStatGT([PC],0,GREASE)
        CheckStatGT([PC],0,WEB)
THEN
    RESPONSE #70
        Spell([PC],CLERIC_FREE_ACTION)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
    RESPONSE #30
        Continue()
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    OR(3)
        StateCheck([PC],STATE_STUNNED)
        CheckStatGT([PC],0,HELD)
        CheckStatGT([PC],0,LEVELDRAIN)
    HaveSpell(CLERIC_RESTORATION) 
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_RESTORATION)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    See([PC])
    HaveSpell(CLERIC_LESSER_RESTORATION)
    OR(3)
        StateCheck([PC],STATE_STUNNED)
        CheckStatGT([PC],0,HELD)
        CheckStatGT([PC],0,LEVELDRAIN)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")

    THEN
        RESPONSE #100
        Spell([PC],CLERIC_LESSER_RESTORATION)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// Heal Critical Wounds
IF
    ActionListEmpty()
    See([PC])
    HPPercentLT([PC],50) // Heal when HP is below 20
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)
THEN
    RESPONSE #100
        Spell([PC],CLERIC_CURE_CRITICAL_WOUNDS)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND) // Set a 2-minute timer
END

IF
    ActionListEmpty()
    See([PC])
    HPPercentLT([PC],75)
    HaveSpell(PALADIN_LAY_ON_HANDS)  // 4211 (PALADIN_LAY_ON_HANDS)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell([PC],PALADIN_LAY_ON_HANDS)  // Cast PALADIN_LAY_ON_HANDS
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// ======================================================
//  SECTIONL: Heal (WIZARD)
// ======================================================

IF
    ActionListEmpty()
    HaveSpell(WIZARD_DISPEL_MAGIC)  // SPPR303.SPL (Dispel Magic)
    See([PC])
    OR(4)
        StateCheck(LastSeenBy(Myself),STATE_CHARMED)
        StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
        StateCheck(LastSeenBy(Myself),STATE_STUNNED)
        CheckStatGT(LastSeenBy(Myself),0,HELD)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)  // SPPR303.SPL (Dispel Magic)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND) // Set a 2-minute timer
END



// ======================================================
// SECTION: Heal ITEMS 
// ======================================================

// potion of superior healing
IF
    ActionListEmpty()
    ActuallyInCombat()
    HPPercentLT(Myself,25)
    PartyHasItem("POTN55")  
THEN
    RESPONSE #100
        TakePartyItemNum("POTN55",1)
        UseItem("POTN55",Myself)  
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HPPercentLT(Myself,50)
    PartyHasItem("POTN52")  
THEN
    RESPONSE #100
        TakePartyItemNum("POTN52")
        UseItem("POTN52",Myself) 
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HPPercentLT(Myself,50)
    PartyHasItem("POTN08") 
THEN
    RESPONSE #100
        TakePartyItemNum("POTN08",1)
        UseItem("POTN08",Myself)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HPPercentLT(Myself,35)
    !StateCheck(Myself,STATE_INVISIBLE)
    PartyHasItem("POTN10")  // Potion of Invisibility
THEN
    RESPONSE #100
        TakePartyItemNum("POTN10",1)
        UseItem("POTN10",Myself)  
        RunAwayFrom(NearestEnemyOf(Myself),75)
END

IF
    ActionListEmpty()
    !CheckSpellState(Myself,POTION_OF_CLARITY)
    !ExtendedStateCheck(Myself,STATE_CHAOTIC_COMMANDS)
    CheckStatLT(Myself,1,CLERIC_CHAOTIC_COMMANDS)    
    GlobalTimerNotExpired("PSYCHIC_ENEMIES","LOCALS")
    PartyHasItem("POTN21")  // Potion of Clarity
    OR(2)
        Class(Myself,FIGHTER)
        Class(Myself,PALADIN)
    Delay(60)
THEN
    RESPONSE #100
        TakePartyItemNum("POTN21",1)
        UseItem("POTN21",Myself)  
END

//Potion of Speed
IF
    ActionListEmpty()
    ActuallyInCombat()
    !StateCheck(Myself,STATE_HASTED)
    PartyHasItem("POTN23")
    HPGT([ENEMY],60)
    OR(2)
        NumCreatureGT([ENEMY],4)
        LevelGT([ENEMY],5)
    OR(4)
        Class(Myself,FIGHTER)
        Class(Myself,RANGER)
        Class(Myself,THIEF)
        Class(Myself,PALADIN)
    Delay(60)
THEN
    RESPONSE #50
        Continue()
    RESPONSE #50
        TakePartyItemNum("POTN23",1)
        UseItem("POTN23",Myself)  
END

//Potion of Speed
IF
    ActionListEmpty()
    ActuallyInCombat()
    !StateCheck(Myself,STATE_HASTED)
    PartyHasItem("POTN14")
    HPGT([ENEMY],60)
    OR(2)
        NumCreatureGT([ENEMY],4)
        LevelGT([ENEMY],5)
    OR(4)
        Class(Myself,FIGHTER)
        Class(Myself,RANGER)
        Class(Myself,THIEF)
        Class(Myself,PALADIN)
    Delay(60)
THEN
    RESPONSE #50
        Continue()
    RESPONSE #50
        TakePartyItemNum("POTN14",1)
        UseItem("POTN14",Myself)  
END

//Potion of Heroism 
IF
    ActionListEmpty()
    ActuallyInCombat()
    PartyHasItem("POTN09")
    LevelGT([ENEMY],7)
    HPGT([ENEMY],70)
    OR(4)
        Class(Myself,FIGHTER)
        Class(Myself,RANGER)
        Class(Myself,THIEF)
        Class(Myself,PALADIN)
    Delay(60)
THEN
    RESPONSE #50
        Continue()
    RESPONSE #50
        TakePartyItemNum("POTN09",1)
        UseItem("POTN09",Myself)  
END

// Potion of Defence (24)

//Potion of Heroism 
IF
    ActionListEmpty()
    ActuallyInCombat()
    PartyHasItem("POTN24")
    LevelGT([ENEMY],7)
    HPGT([ENEMY],70)
    CheckStatGT(Myself,0,ARMORCLASS)
    Delay(60)
THEN
    RESPONSE #50
        Continue()
    RESPONSE #50
        TakePartyItemNum("POTN24",1)
        UseItem("POTN24",Myself)  
END

IF
    ActionListEmpty()
    !CheckSpellState(Myself,FREE_ACTION)
    CheckStatLT(Myself,1,CLERIC_FREE_ACTION)    
    Delay(100)
    GlobalTimerNotExpired("PSYCHIC_ENEMIES","LOCALS")
    PartyHasItem("POTN45")  // Potion of Freedom
THEN
    RESPONSE #100
        TakePartyItemNum("POTN45",1)
        UseItem("POTN45",Myself)  
END

//Poison Management
IF
    StateCheck(Myself,STATE_POISONED)
    PartyHasItem("POTN20") // Antidote
THEN
    RESPONSE #100
        TakePartyItemNum("POTN20",1)
        UseItem("POTN20",Myself) // Antidote
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    StateCheck(Myself,STATE_POISONED)
    GlobalLT("USED_AMUL22","LOCALS",1)
    HasItemEquiped("AMUL22",Myself) 
THEN
    RESPONSE #100
      SetInterrupt(FALSE)
      UseItem("AMUL22",Myself)  
      SetInterrupt(TRUE)
      IncrementGlobal("USED_AMUL22","LOCALS",1)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    See([PC])
    StateCheck(LastSeenBy(Myself),STATE_POISONED)
    GlobalLT("USED_AMUL22","LOCALS",1)
    HasItemEquiped("AMUL22",Myself) 
THEN
    RESPONSE #100
      SetInterrupt(FALSE)
      UseItem("AMUL22",LastSeenBy(Myself))  
      SetInterrupt(TRUE)
      IncrementGlobal("USED_AMUL22","LOCALS",1)
END

//Innate cure poison
IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpellRES("SPIN102")  
    StateCheck([PC],STATE_POISONED)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        SpellRES("SPIN102",[PC])  // Cast Holy Power for increased strength
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    OR(2)
        HPPercentLT(Myself,60)
        StateCheck(Myself,STATE_POISONED)
    PartyHasItem("POTN17") // Elixir of Health
THEN
    RESPONSE #100
        TakePartyItemNum("POTN17",1)
        UseItem("POTN17",Myself) // Elixir of Health
END


// ======================================================
// SECTION: PENETRATION SPELLS (WIZARD)
// ======================================================

IF
    ActuallyInCombat()
    ActionListEmpty()
    OR(6)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.RAKSHASA])    
    HaveSpell(WIZARD_SPELL_STRIKE)  
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See([ENEMY])
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !ImmuneToSpellLevel(LastSeenBy(Myself),5)
    OR(5)
        CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
        CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
        CheckSpellState(LastSeenBy(Myself),MANTLE)
        CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
        CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    HaveSpell(WIZARD_BREACH)
    THEN
        RESPONSE #100
        SetInterrupt(FALSE)
        Spell(LastSeenBy(Myself),WIZARD_BREACH)  
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        SetInterrupt(TRUE)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See([ENEMY])
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !ImmuneToSpellLevel(LastSeenBy(Myself),5)
    OR(5)
        CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
        CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
        CheckSpellState(LastSeenBy(Myself),MANTLE)
        CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
        CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    HaveSpellRES("SPWI302") //Use spell res here, otherwise the game can't find the id in bgee 1. In 2 it exists. 
    THEN
        RESPONSE #100
        SetInterrupt(FALSE)
        SpellRES("SPWI302",LastSeenBy(Myself))  
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        SetInterrupt(TRUE)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See([ENEMY])
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !ImmuneToSpellLevel(LastSeenBy(Myself),5)
    OR(5)
        CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
        CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
        CheckSpellState(LastSeenBy(Myself),MANTLE)
        CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
        CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    HaveSpell(WIZARD_DISPEL_MAGIC)
    THEN
        RESPONSE #100
        SetInterrupt(FALSE)
        Spell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        SetInterrupt(TRUE)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See([ENEMY])
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !ImmuneToSpellLevel(LastSeenBy(Myself),3)
    OR(5)
        CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
        CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
        CheckSpellState(LastSeenBy(Myself),MANTLE)
        CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
        CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    HaveSpell(WIZARD_SPELL_THRUST)
    THEN
        RESPONSE #100
        SetInterrupt(FALSE)
        Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        SetInterrupt(TRUE)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See([ENEMY])
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !ImmuneToSpellLevel(LastSeenBy(Myself),4)
    OR(5)
        CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
        CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
        CheckSpellState(LastSeenBy(Myself),MANTLE)
        CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
        CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    HaveSpell(WIZARD_SECRET_WORD)
    THEN
        RESPONSE #100
        SetInterrupt(FALSE)
        Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)  
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        SetInterrupt(TRUE)
END
IF

    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
    !Difficulty(EASIEST)
    OR(3)
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.BARD_ALL])
        See([ENEMY.0.0.MAGE_ALL])
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !HasItemEquiped("AMUL21",LastSeenBy(Myself))  // Amulet of Power
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
END

IF
    ActuallyInCombat()
    ActionListEmpty()  
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    HaveSpell(WIZARD_GLITTERDUST)  // SPWI224.SPL (Glitterdust)
    !See([ENEMY])
    Detect([ENEMY])
    Range(LastSeenBy(Myself),12)
    CheckStatLT(LastSeenBy(Myself),60,STEALTH)
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    !HasItemEquiped("NPMISC1",LastSeenBy(Myself))  // Jansen Spectroscopes
THEN
    RESPONSE #100
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_GLITTERDUST)  // SPWI224.SPL (Glitterdust)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    OR(6)
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.BARD_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.SORCERER])
        See([ENEMY.0.0.RAKSHASA])    
    HaveSpell(WIZARD_PIERCE_MAGIC)  
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    OR(6)
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.BARD_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.SORCERER])
        See([ENEMY.0.0.RAKSHASA])    
    HaveSpell(WIZARD_WARDING_WHIP)  
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_WARDING_WHIP)  // Cast WIZARD_WARDING_WHIP
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    OR(6)
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.BARD_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.SORCERER])
        See([ENEMY.0.0.RAKSHASA])    
    HaveSpell(WIZARD_PIERCE_MAGIC)  // 2608 (WIZARD_PIERCE_MAGIC)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // Cast WIZARD_PIERCE_MAGIC
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


// ======================================================
// SECTION PENETRATION SPELLS (CLERIC)
// ======================================================

IF
    ActionListEmpty()
    OR(6)
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.BARD_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.SORCERER])
        See([ENEMY.0.0.RAKSHASA])
    ActuallyInCombat()
    ActionListEmpty()
    HaveSpell(CLERIC_DISPEL_MAGIC)  // 1303 (CLERIC_DISPEL_MAGIC)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_DISPEL_MAGIC)  // Cast CLERIC_DISPEL_MAGIC
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    OR(7)
        See([ENEMY])
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.BARD_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.SORCERER])
        See([ENEMY.0.0.RAKSHASA])
    OR(7)
        CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
        CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
        CheckSpellState(LastSeenBy(Myself),MANTLE)
        CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
        CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
        CheckSpellState(LastSeenBy(Myself),RED_FIRESHIELD)
        CheckSpellState(LastSeenBy(Myself),BLUE_FIRESHIELD)

    HaveSpell(INQUIS_DISPEL_MAGIC)  // 4231 (INQUIS_DISPEL_MAGIC)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(LastSeenBy(Myself),INQUIS_DISPEL_MAGIC)  // Cast INQUIS_DISPEL_MAGIC
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    OR(7)
        See([ENEMY])
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.BARD_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.SORCERER])
        See([ENEMY.0.0.RAKSHASA])
    OR(7)
        CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
        CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
        CheckSpellState(LastSeenBy(Myself),MANTLE)
        CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
        CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
        CheckSpellState(LastSeenBy(Myself),RED_FIRESHIELD)
        CheckSpellState(LastSeenBy(Myself),BLUE_FIRESHIELD)

        HaveSpellRES("SPIN112")  // 4231 (INQUIS_DISPEL_MAGIC)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        SpellRES("SPIN112",LastSeenBy(Myself))  // Cast INQUIS_DISPEL_MAGIC
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    OR(7)
        Gender(LastSeenBy(Myself),ILLUSIONARY)
        SpellCast([ENEMY],WIZARD_PROJECT_IMAGE) 
        SpellCast([ENEMY],WIZARD_SIMULACRUM)  
        SpellCast([ENEMY],WIZARD_MISLEAD)  
        StateCheck(LastSeenBy(Myself),STATE_BLUR)
        StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
        Class([ENEMY],THIEF_ALL)
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")
    Delay(30)
    HaveSpell(INQUIS_TRUE_SIGHT) 
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(Myself,INQUIS_TRUE_SIGHT)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    OR(6)
        SpellCast([ENEMY],WIZARD_PROJECT_IMAGE)  // SPWI703.SPL (Project Image)
        SpellCast([ENEMY],WIZARD_SIMULACRUM)  // SPWI804.SPL (Simulacrum)
        SpellCast([ENEMY],WIZARD_MISLEAD)  // SPWI607.SPL (Mislead)
        SpellCast([ENEMY],WIZARD_SHADOW_DOOR)  // SPWI505.SPL (Shadow Door)
        SpellCast([ENEMY],WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (Improved Invisibility)
        SpellCast([ENEMY],WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
    HaveSpell(CLERIC_INVISIBILITY_PURGE)
    THEN
        RESPONSE #100
        Spell([ENEMY],CLERIC_INVISIBILITY_PURGE)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    OR(6)
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.BARD_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.SORCERER])
        See([ENEMY.0.0.RAKSHASA])
    HaveSpell(CLERIC_CREEPING_DOOM) 
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_CREEPING_DOOM) 
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    OR(6)
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.BARD_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.SORCERER])
        See([ENEMY.0.0.RAKSHASA])
    HaveSpell(CLERIC_INSECT_PLAGUE) 
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_INSECT_PLAGUE)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(CLERIC_DOOM)  
    CheckSpellState([ENEMY],DOOM)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell([ENEMY],CLERIC_DOOM)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    OR(6)
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.BARD_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.SORCERER])
        See([ENEMY.0.0.RAKSHASA])
    HaveSpell(CLERIC_SILENCE_15_FOOT)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    OR(6)
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.BARD_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.SORCERER])
        See([ENEMY.0.0.RAKSHASA])
    HaveSpell(CLERIC_MISCAST_MAGIC)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_MISCAST_MAGIC)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// ======================================================
// SECTION: SUMMONING SPELLS (CLERIC)
// ======================================================

// CLERIC_ETHER_GATE
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_ETHER_GATE)
    CheckSpellState(Myself,PROTECTION_FROM_EVIL)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_ETHER_GATE)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_SUMMON_DEVA
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_SUMMON_DEVA)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_SUMMON_DEVA)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    HaveSpell(PALADIN_SUMMON_DEVA)  // 4923 (PALADIN_SUMMON_DEVA)
    Range(NearestEnemyOf(Myself),30)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")

    THEN
        RESPONSE #100
        Spell(NearestEnemyOf(Myself),PALADIN_SUMMON_DEVA)  // Cast PALADIN_SUMMON_DEVA
        SetGlobalTimer("UNKNOWN_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_SUMMON_FALLEN_DEVA
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_SUMMON_FALLEN_DEVA)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_SUMMON_FALLEN_DEVA)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_CONJURE_FIRE_ELEMENTAL
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_CONJURE_FIRE_ELEMENTAL)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CONJURE_FIRE_ELEMENTAL)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_CONJURE_EARTH_ELEMENTAL
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_CONJURE_EARTH_ELEMENTAL)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CONJURE_EARTH_ELEMENTAL)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_GATE
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    CheckSpellState(Myself,PROTECTION_FROM_EVIL)
    HaveSpell(CLERIC_GATE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_GATE)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(TOTEMIC_DRUID_SUMMON_SPIRIT_ANIMAL)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,TOTEMIC_DRUID_SUMMON_SPIRIT_ANIMAL)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END


IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_ANIMATE_DEAD)
    CheckStatLT(Myself,1,DEAD_MAGIC)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_ANIMATE_DEAD)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_ANIMAL_SUMMONING_1
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_ANIMAL_SUMMONING_1)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_ANIMAL_SUMMONING_1)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_CALL_WOODLAND_BEINGS
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_CALL_WOODLAND_BEINGS)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CALL_WOODLAND_BEINGS)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_ANIMAL_SUMMONING_2
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_ANIMAL_SUMMONING_2)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_ANIMAL_SUMMONING_2)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_AERIAL_SERVANT
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_AERIAL_SERVANT)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_AERIAL_SERVANT)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_ANIMAL_SUMMONING_3
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_ANIMAL_SUMMONING_3)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_ANIMAL_SUMMONING_3)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_CONJURE_ANIMALS
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_CONJURE_ANIMALS)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CONJURE_ANIMALS)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_ELEMENTAL_SWARM
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_ELEMENTAL_SWARM)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_ELEMENTAL_SWARM)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_GREATER_ELEMENTAL_SWARM
IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(CLERIC_GREATER_ELEMENTAL_SWARM)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_GREATER_ELEMENTAL_SWARM)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// ======================================================
// SECTION: SUMMONING SPELLS (WIZARD)
// ======================================================

IF
    ActionListEmpty()
    HaveSpell(WIZARD_SUMMON_PLANATAR_EVIL)  // SPWI615.SPL (Summon Hakeashar)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    GlobalTimerNotExpired("SUMMON","LOCALS")
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_SUMMON_PLANATAR_EVIL)  // Summon Hakeashar to disrupt enemy spellcasting
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_SUMMON_PLANATAR_GOOD)  // SPWI615.SPL (Summon Hakeashar)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_SUMMON_PLANATAR_GOOD)  // Summon Hakeashar to disrupt enemy spellcasting
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_GATE)  // SPWI615.SPL (Summon Hakeashar)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckSpellState(Myself,PROTECTION_FROM_EVIL)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_GATE)  // Summon Hakeashar to disrupt enemy spellcasting
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(WIZARD_SUMMON_FIEND)  // SPWI615.SPL (Summon Hakeashar)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckSpellState(Myself,PROTECTION_FROM_EVIL)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    GlobalTimerNotExpired("SUMMON","LOCALS")
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_SUMMON_FIEND)  // Summon Hakeashar to disrupt enemy spellcasting
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell( WIZARD_SIMULACRUM)  // SPWI615.SPL (Summon Hakeashar)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    GlobalTimerNotExpired("SUMMON","LOCALS")
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself, WIZARD_SIMULACRUM)  // Summon Hakeashar to disrupt enemy spellcasting
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


IF
    ActionListEmpty()
    HaveSpell(WIZARD_SUMMON_DJINNI)  // SPWI615.SPL (Summon Hakeashar)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    GlobalTimerNotExpired("SUMMON","LOCALS")
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_SUMMON_DJINNI)  // Summon Hakeashar to disrupt enemy spellcasting
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_SUMMON_HAKEASHAR)  // SPWI615.SPL (Summon Hakeashar)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_SUMMON_HAKEASHAR)  // Summon Hakeashar to disrupt enemy spellcasting
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_SUMMON_EFREET)  // SPWI615.SPL (Summon Hakeashar)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_SUMMON_EFREET)  // Summon Hakeashar to disrupt enemy spellcasting
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_MORDENKAINENS_SWORD)  // SPWI615.SPL (Summon Hakeashar)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_MORDENKAINENS_SWORD)  // Summon Hakeashar to disrupt enemy spellcasting
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_CACOFIEND) 
    NumCreatureLT([GOODCUTOFF.0.0.0.0.SUMMONED],3)
    CheckSpellState(Myself,PROTECTION_FROM_EVIL)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_CACOFIEND)  // Summon Hakeashar to disrupt enemy spellcasting
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    NumCreatureLT([GOODCUTOFF.0.0.0.0.SUMMONED],6)
    HaveSpell(WIZARD_CONJURE_EARTH_ELEMENTAL) 
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_CONJURE_EARTH_ELEMENTAL) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    NumCreatureLT([GOODCUTOFF.0.0.0.0.SUMMONED],6)
    HaveSpell(WIZARD_CONJURE_AIR_ELEMENTAL) 
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_CONJURE_AIR_ELEMENTAL) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    NumCreatureLT([GOODCUTOFF.0.0.0.0.SUMMONED],6)
    HaveSpell(WIZARD_CONJURE_FIRE_ELEMENTAL) 
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_CONJURE_FIRE_ELEMENTAL) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    NumCreatureLT([GOODCUTOFF.0.0.0.0.SUMMONED],3)
    HaveSpell(WIZARD_CARRION) 
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_CARRION) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_WYVERN_CALL) 
    NumCreatureLT([GOODCUTOFF.0.0.0.0.SUMMONED],3)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_WYVERN_CALL)  // Summon Hakeashar to disrupt enemy spellcasting
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_SUMMON_NISHRUU)  
    NumCreatureLT([GOODCUTOFF.0.0.0.0.SUMMONED],3)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_SUMMON_NISHRUU) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_INVISIBLE_STALKER) 
    NumCreatureLT([GOODCUTOFF.0.0.0.0.SUMMONED],3)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_INVISIBLE_STALKER)  
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_ANIMATE_DEAD)  
    NumCreatureLT([GOODCUTOFF.0.0.0.0.SUMMONED],3)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_ANIMATE_DEAD) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

//Summon Ghast Tiax!
IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpellRES("SPIN115")
    NumCreatureLT([GOODCUTOFF.0.0.0.0.SUMMONED],3)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        SpellRES("SPIN115",[ANYONE])  
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_MONSTER_SUMMONING_3) 
    NumCreatureLT([GOODCUTOFF.0.0.0.0.SUMMONED],3)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_MONSTER_SUMMONING_3) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_SPIDER_SPAWN)  
    NumCreatureLT([GOODCUTOFF.0.0.0.0.SUMMONED],3)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_SPIDER_SPAWN)  // Summon spiders to aid in combat
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_MONSTER_SUMMONING_2)  // SPWI511.SPL (Monster Summoning II)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_MONSTER_SUMMONING_2)  // Summon stronger monsters to assist in combat
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_MONSTER_SUMMONING_1)  // SPWI103.SPL (Summon Monster I)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_MONSTER_SUMMONING_1)  // Summon a monster to assist in combat
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SUMMON","LOCALS")
    HaveSpell(WIZARD_FIND_FAMILAR)  // SPWI123.SPL (Find Familiar)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckSpellState(Myself,DEAD_MAGIC_AREA)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_FIND_FAMILAR)  // Summon a familiar to assist
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END



// ======================================================
// SECTION: Short Duration BUFFS (WIZARD)
// ======================================================
IF
    ActionListEmpty()
    HaveSpell(WIZARD_CHAOS_SHIELD) 
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")  
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_CHAOS_SHIELD)  
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND) 
END

// Cast Haste if conditions are met
IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(WIZARD_HASTE)  // Ensure the Haste spell is available
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")  // Ensure previous spell cast timer has expired
    !StateCheck(Myself,STATE_HASTED)  // Ensure Haste is not already active
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_HASTE)  // Cast Haste on Myself
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)  // Set timer to prevent repeated casting
END


IF
    ActionListEmpty()
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI604.SPL (Globe of Invulnerability)
    //If any spell is cast by an enemy then this is useful
    OR(2)
        SpellCast([ENEMY],0)
        !GlobalTimerNotExpired("CASTER_ENEMY","LOCALS")
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // Cast Globe of Invulnerability for spell protection
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)  
    //If any spell is cast by an enemy then this is useful
    OR(2)
        SpellCast([ENEMY],0)
        !GlobalTimerNotExpired("CASTER_ENEMY","LOCALS")
    Range(NearestEnemyOf(Myself),30)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION) 
    !HasBounceEffects(Myself)
    !HasImmunityEffects(Myself)
        //If any spell is cast by an enemy then this is useful
    OR(2)
        SpellCast([ENEMY],0)
        GlobalTimerNotExpired("CASTER_ENEMY","LOCALS")
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


IF
    ActionListEmpty()
    HaveSpell(WIZARD_SPELL_DEFLECTION)  
    !HasBounceEffects(Myself)
    !HasImmunityEffects(Myself)
        //If any spell is cast by an enemy then this is useful
    OR(2)
        SpellCast([ENEMY],0)
        GlobalTimerNotExpired("CASTER_ENEMY","LOCALS")
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_SPELL_DEFLECTION)  
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(WIZARD_MINOR_SPELL_TURNING)  // SPWI522.SPL (Minor Spell Turning)
    !HasBounceEffects(Myself)
    !HasImmunityEffects(Myself)
    //If any spell is cast by an enemy then this is useful
    OR(2)
        SpellCast([ENEMY],0)
        !GlobalTimerNotExpired("CASTER_ENEMY","LOCALS")
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    GlobalTimerNotExpired("CASTER_ENEMY","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_MINOR_SPELL_TURNING)  // Cast Minor Spell Turning
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
    !HasBounceEffects(Myself)
    !HasImmunityEffects(Myself)
    //If any spell is cast by an enemy then this is useful
    OR(2)
        SpellCast([ENEMY],0)
        !GlobalTimerNotExpired("CASTER_ENEMY","LOCALS")
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    GlobalTimerNotExpired("CASTER_ENEMY","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_SPELL_TURNING)  // Cast Spell Turning
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(WIZARD_LIMITED_WISH) 
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS") 
    THEN
        RESPONSE #100
        Spell(Myself,WIZARD_LIMITED_WISH)  // Cast WIZARD_LIMITED_WISH
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
    !StateCheck(Myself,STATE_INVISIBLE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_INVISIBILITY)  // Cast Invisibility if not already invisible
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_IMPROVED_INVISIBILITY)  // SPWI206.SPL (Invisibility)
    !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
    !StateCheck(Myself,STATE_INVISIBLE)
    DamageTaken(10)
    HPPercentLT(Myself,90)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // Cast Invisibility if not already invisible
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(WIZARD_MASS_INVISIBILITY)  // 2721 (WIZARD_MASS_INVISIBILITY)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    THEN
        RESPONSE #100
        Spell(Myself,WIZARD_MASS_INVISIBILITY)  // Cast WIZARD_MASS_INVISIBILITY
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(WIZARD_MIRROR_IMAGE)  // 2721 (WIZARD_MASS_INVISIBILITY)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS") 
    THEN
        RESPONSE #100
            Spell(Myself,WIZARD_MIRROR_IMAGE)  // Cast WIZARD_MASS_INVISIBILITY
            SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


IF
    ActionListEmpty()
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    HaveSpell(WIZARD_ENERGY_BLADES)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself, WIZARD_ENERGY_BLADES)  // Cast Energy Blades
        Continue()
END


//This disables spell casting
IF
    ActuallyInCombat()
    ActionListEmpty()
    HaveSpell(WIZARD_SHAPECHANGE)  // 2916 (WIZARD_SHAPECHANGE)
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS") 
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
            Spell(Myself,WIZARD_SHAPECHANGE)  // Cast WIZARD_SHAPECHANGE
            SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(WIZARD_FIRE_SHIELD_BLUE)  
    OR(2)
        TookDamage()
        Range([ENEMY],8)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS") 
    THEN
        RESPONSE #100
            Spell(Myself,WIZARD_FIRE_SHIELD_BLUE)  
            SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(WIZARD_STRENGTH)  
    Range([ENEMY],8)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS") 
    THEN
        RESPONSE #100
            Spell(Myself,WIZARD_STRENGTH)  
            SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(WIZARD_FIRE_SHIELD_RED)  
    OR(2)
        TookDamage()
        Range([ENEMY],8)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS") 
    THEN
        RESPONSE #100
            Spell(Myself,WIZARD_FIRE_SHIELD_RED)  
            SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(WIZARD_PROTECTION_FROM_FIRE)  
    HitBy([ANYONE],FIRE)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS") 
    THEN
        RESPONSE #100
            Spell(Myself,WIZARD_PROTECTION_FROM_FIRE)  
            SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


IF
    ActuallyInCombat()
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_IMPROVED_HASTE)  // 2613 (WIZARD_IMPROVED_HASTE)
    Range(NearestEnemyOf(Myself),30)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(Myself,WIZARD_IMPROVED_HASTE)  // Cast WIZARD_IMPROVED_HASTE
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

// Cast Blur if conditions are met
IF
    ActionListEmpty()
    HaveSpell(WIZARD_BLUR)  // Ensure the Blur spell is available
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")  // Ensure previous spell cast timer has expired
    !StateCheck(Myself,STATE_BLUR)  // Ensure Blur is not already active
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_BLUR)  // Cast Blur on Myself
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)  // Set timer to prevent repeated casting
END



// Cast Luck if conditions are met
IF
    ActionListEmpty()
    HaveSpell(WIZARD_LUCK)  // Ensure the Luck spell is available
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")  // Ensure previous spell cast timer has expired
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_LUCK)  // Cast Luck on Myself
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)  // Set timer to prevent repeated casting
END



// Cast Melf's Minute Meteors if conditions are met
IF
    ActionListEmpty()
    HaveSpell(WIZARD_MELF_METEOR)  // Ensure Melf's Minute Meteors spell is available
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")  // Ensure previous spell cast timer has expired
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_MELF_METEOR)  // Cast Melf's Minute Meteors on Myself
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)  // Set timer to prevent repeated casting
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    StateCheck(Myself,STATE_SILENCED)
    HaveSpell(WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_VOCALIZE)  // Cast Vocalize if silenced
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See([ENEMY])
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    HaveSpell(WIZARD_PROTECTION_FROM_EVIL)  // Ensure the spell is available
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_PROTECTION_FROM_EVIL) // Cast Protection from Evil on Myself
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


// ======================================================
// SECTION: Short Duration BUFFS (CLERIC)
// ======================================================


IF
    ActionListEmpty()
    ActuallyInCombat()
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
    !CheckSpellState(Myself,ARMOR_OF_FAITH)  // Correct spell state for Armor of Faith
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_ARMOR_OF_FAITH)  // Cast Armor of Faith
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(CLERIC_DEFENSIVE_HARMONY)  

    !CheckStatLT([PC],1,CLERIC_DEFENSIVE_HARMONY)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([PC],CLERIC_DEFENSIVE_HARMONY)  // Cast Protection from Fire on yourself
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(CLERIC_DEATH_WARD)  
    See([PC])
    !CheckSpellState(Myself,DEATH_WARD) 
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_DEATH_WARD)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    OR(2)
        ActuallyInCombat()
        GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  
    HaveSpell(CLERIC_CHANT)  
    !StateCheck([PC],STATE_CHANT)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([PC],CLERIC_CHANT)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    OR(2)
        ActuallyInCombat()
        GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  
    !StateCheck([PC],STATE_BLESS)
    HaveSpell(CLERIC_BLESS)  
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([PC],CLERIC_BLESS)  // Cast Protection from Fire on yourself
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpellRES("ohtmps2")
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        SpellRES("ohtmps2",Myself)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(CLERIC_SANCTUARY)  // SPPR109.SPL (Sanctuary)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HPPercentLT(Myself,60)  // Party member's HP is below 25%
      // The target was last seen by the cleric
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_SANCTUARY)  // Cast Sanctuary on the party member with low HP
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(CLERIC_PROTECTION_FROM_EVIL_10_FOOT)  // SPPR107.SPL (Protection from Evil)
    !CheckSpellState(Myself,PROTECTION_FROM_EVIL)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_PROTECTION_FROM_EVIL_10_FOOT)  // Cast Protection from Evil
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(PALADIN_PROTECTION_FROM_EVIL)  // SPPR107.SPL (Protection from Evil)
    !CheckSpellState(Myself,PROTECTION_FROM_EVIL)
    !CheckStatGT(Myself,0,PROTECTION_FROM_EVIL)
    CheckStatLT(Myself,1,DEAD_MAGIC)  
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    Delay(60)//Wait a minute because this spell doesn't set the protection from evil flag correctly
THEN
    RESPONSE #100
        Spell(Myself,PALADIN_PROTECTION_FROM_EVIL)  // Cast Protection from Evil
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
        Continue()
END

IF
    ActionListEmpty()
    HaveSpell(CLERIC_PROTECTION_FROM_FIRE)  
    HitBy([ANYONE],FIRE)
    GlobalTimerNotExpired("FIRE_ENEMIES","LOCALS")  // Timer expired
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_PROTECTION_FROM_FIRE)  // Cast Protection from Fire on yourself
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    See([PC])
    !CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
    HaveSpell(CLERIC_PROTECTION_FROM_FIRE)  
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_PROTECTION_FROM_FIRE)  // Cast Protection from Fire on yourself
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(CLERIC_BARKSKIN)  
    See([PC])
    !CheckSpellState(LastSeenBy(Myself),BARKSKIN)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_BARKSKIN)  // Cast Protection from Fire on yourself
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

//Long term buff, remove fear works for 1 hour and removes the fear and blocks it.
IF
    ActionListEmpty()
    HaveSpell(CLERIC_REMOVE_FEAR) 
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")  
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_REMOVE_FEAR)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(CLERIC_PIXIE_DUST)  
    See([PC])
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_PIXIE_DUST)  // Cast Protection from Fire on yourself
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(CLERIC_IRONSKIN)  
    See([PC])
    !CheckSpellState(LastSeenBy(Myself),IRON_SKINS)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_IRONSKIN)  // Cast Protection from Fire on yourself
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(CLERIC_FLAME_BLADE)  
    OR(2)
        GlobalTimerNotExpired("TROLL_ENEMIES","LOCALS")
        LevelLT(Myself,8)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_FLAME_BLADE)  // Cast Protection from Fire on yourself
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

//Blackguard innate abilities
IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(ASSASSIN_POISON)  
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    Delay(30)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,ASSASSIN_POISON) 
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(AURA_OF_DESPAIR)  
    OR(2)
        LevelGT([ENEMY],2)
        NumCreatureGT([ENEMY],1)
    Range([ENEMY],10)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    Delay(10)
THEN
    RESPONSE #100
        Spell(Myself,AURA_OF_DESPAIR)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(CLERIC_SPIRITUAL_HAMMER)  
    OR(3)
        HasItemEquiped("HAMM01",Myself) // Basic War Hammer
        HasItemEquiped("HAMM02",Myself) // War Hammer +1 (if you also want to replace this)
        HasItemEquiped("IHAMM01",Myself) // Improved hammer, only from beregost smith after nashkel mine quest
    InWeaponRange(NearestEnemyOf(Myself))
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_SPIRITUAL_HAMMER)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpellRES("SPIN113")
    OR(3)
        HasItemEquiped("HAMM01",Myself) // Basic War Hammer
        HasItemEquiped("HAMM02",Myself) // War Hammer +1 (if you also want to replace this)
        HasItemEquiped("IHAMM01",Myself) // Improved hammer, only from beregost smith after nashkel mine quest
    InWeaponRange(NearestEnemyOf(Myself))  
    CheckStatGT(Myself,3,THAC0)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    Delay(30)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        SpellRES("SPIN113",Myself)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(CLERIC_SANCTUARY)  
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HPPercentLT(Myself,50)  
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_SANCTUARY)  // Cast Sanctuary on the party member with low HP
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(CLERIC_SANCTUARY)  // SPPR109.SPL (Sanctuary)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    HPPercentLT([PC],50)  // Party member's HP is below 25%
THEN
    RESPONSE #100
        Spell([PC],CLERIC_SANCTUARY)  // Cast Sanctuary on the party member with low HP
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END



IF
    ActionListEmpty()
    ActuallyInCombat()
    See(NearestEnemyOf(Myself))
    HaveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection from Evil)
    !CheckSpellState(Myself,PROTECTION_FROM_EVIL)  // Correct spell state for Protection from Evil
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_PROTECT_FROM_EVIL)  // Cast Protection from Evil
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

//CHAOS OF BATTLE: Chaos of Battle applies bonuses to all allies and penalties to all enemies within a 30-ft. radius of the caster. The spell lasts 1 turn and will randomly affect the targets' Armor Class, Hit Points, THAC0, saves, or luck. The magnitude of the effect starts at 1 (5 for Hit Points) at level 1 and will improve by 1 (5 for Hit Points) every 6 levels of the caster.
IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpellRES("OHTMPS2")  
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    Delay(30)
THEN
    RESPONSE #100
        SpellRES("OHTMPS2",Myself) 
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

//BOON OF LATHANDER: This spell lasts 1 round per level of the caster. It gives the caster a +1 bonus to attack and damage rolls, a +1 bonus to all Saving Throws, and 1 extra attack per round. It also protects the recipient from level drain.
IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(LATHANDER_BOON)  
    !CheckSpellState(Myself,LATHANDER_BOON) 
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,LATHANDER_BOON)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(CLERIC_HOLY_POWER)  
    !CheckSpellState(Myself,HOLY_POWER)  // State 9 for Holy Power
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_HOLY_POWER)  // Cast Holy Power for increased strength
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpellRES("ohtmps1")  
    !CheckSpellState(Myself,HOLY_POWER)  // State 9 for Holy Power
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        SpellRES("ohtmps1",Myself)  // Cast Holy Power for increased strength
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

//Holy might power
IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpellRES("SPIN103")  
    !CheckSpellState(Myself,HOLY_POWER)  // State 9 for Holy Power
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    Delay(20)
THEN
    RESPONSE #100
        SpellRES("SPIN103",Myself)  // Cast Holy Power for increased strength
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(CLERIC_RIGHTEOUS_MAGIC)  
    !CheckSpellState(Myself,ALLIED_RIGHTEOUS_WRATH_OF_THE_FAITHFUL)  // State 16 for Righteous Wrath of the Faithful (closest match)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_RIGHTEOUS_MAGIC)  // Cast Righteous Magic to increase combat abilities
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(CLERIC_DEATH_WARD)  
    !CheckSpellState(Myself,DEATH_WARD)  // State 8 for Death Ward
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_DEATH_WARD)  // Cast Death Ward to protect from death magic
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(CLERIC_CHAOTIC_COMMANDS)  
    OR(2)
        GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
        GlobalTimerNotExpired("PSYCHIC_ENEMIES","LOCALS")
    !CheckSpellState(Myself,CHAOTIC_COMMANDS)  // State 41 for Chaotic Commands
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_CHAOTIC_COMMANDS)  // Cast Chaotic Commands to protect from mind control
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    See([PC])
    HaveSpell(CLERIC_CHAOTIC_COMMANDS)  
    OR(2)
        GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
        GlobalTimerNotExpired("PSYCHIC_ENEMIES","LOCALS")
    !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)  // State 41 for Chaotic Commands
    CheckStatLT(LastSeenBy(Myself),1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_CHAOTIC_COMMANDS)  // Cast Chaotic Commands to protect from mind control
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  // Timer expired
    HaveSpell(CLERIC_FREE_ACTION)  
    !CheckSpellState(Myself,FREE_ACTION)  // State 29 for Free Action
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_FREE_ACTION)  // Cast Free Action to avoid slow or hold effects
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    See([PC])
    HaveSpell(CLERIC_FREE_ACTION)  
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")  
    !CheckSpellState(LastSeenBy(Myself),FREE_ACTION)  
    GlobalTimerNotExpired("PSYCHIC_ENEMIES","LOCALS")
    CheckStatLT(LastSeenBy(Myself),1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_FREE_ACTION)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// ======================================================
// IN COMBAT SPELLCASTING - Crowd Control (WIZARD)
// ======================================================


IF
    ActionListEmpty()
    ActuallyInCombat()
    LevelGT([ENEMY],4)
    !ImmuneToSpellLevel(LastSeenBy(Myself),4)
    CheckStatLT(LastSeenBy(Myself),100,RESISTMAGIC)
    !HasBounceEffects([ENEMY])
    HaveSpell(WIZARD_GREATER_MALISON) 
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],WIZARD_GREATER_MALISON)  
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


IF
    ActuallyInCombat()
    ActionListEmpty()
    See(LastSeenBy(Myself))
    LevelGT([ENEMY],4)
    !ImmuneToSpellLevel(LastSeenBy(Myself),4)
    CheckStatLT(LastSeenBy(Myself),100,RESISTMAGIC)
    HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
    HPGT(LastSeenBy(Myself),40)
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


IF
    ActuallyInCombat()
    ActionListEmpty()
    HaveSpell(WIZARD_SLEEP)  // SPWI101.SPL (Sleep)
    LevelLT([ENEMY],5)
    !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
    !Race([ENEMY],ELF)  // Exclude elves
    !General(NearestEnemyOf(Myself),UNDEAD)  // Exclude undead
    !See(NearestEnemyOfType([ENEMY.0.GOLEM]))
    !See(NearestEnemyOfType([ENEMY.0.MEPHIT]))
    !CheckSpellState([ENEMY],BERSERKER_RAGE)
    !CheckSpellState([ENEMY],BARBARIAN_RAGE)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    Delay(12)
    THEN
        RESPONSE #100
        Spell([ENEMY],WIZARD_SLEEP)  // Cast Sleep
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    HaveSpell(WIZARD_RAY_OF_ENFEEBLEMENT) 
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],WIZARD_RAY_OF_ENFEEBLEMENT) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


IF
    ActuallyInCombat()
    ActionListEmpty()
    See([ENEMY])
    HaveSpell(WIZARD_SLOW)  
    StateCheck([ENEMY],STATE_SLOWED)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell([ENEMY],WIZARD_SLOW)  
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    HaveSpell(WIZARD_CONTAGION)  // SPWI104.SPL (Contagion)
    HPGT([ENEMY],50)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell([ENEMY],WIZARD_CONTAGION)  // Cast Contagion
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See([ENEMY])
    !ImmuneToSpellLevel(LastSeenBy(Myself),5)
    HaveSpell(WIZARD_CONFUSION)  
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
    !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
    !General(LastSeenBy(Myself),UNDEAD)  // Exclude undead
    !Race(LastSeenBy(Myself),GOLEM)
    !Race(LastSeenBy(Myself),SWORD)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See([ENEMY])
    !ImmuneToSpellLevel(LastSeenBy(Myself),5)
    HaveSpell(WIZARD_CHAOS)  
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
    !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
    !General(LastSeenBy(Myself),UNDEAD)  // Exclude undead
    !Race(LastSeenBy(Myself),GOLEM)
    !Race(LastSeenBy(Myself),SWORD)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_CHAOS) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See([ENEMY])
    !ImmuneToSpellLevel(LastSeenBy(Myself),2)
    HaveSpell(WIZARD_HORROR) 
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
    !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
    !General(LastSeenBy(Myself),UNDEAD)  // Exclude undead
    !Race(LastSeenBy(Myself),GOLEM)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_HORROR) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


IF
    ActuallyInCombat()
    ActionListEmpty()
    HaveSpell(WIZARD_WEB)  // SPWI206.SPL (Web)
    !Race([ENEMY],SPIDER)  // Exclude spiders
    !Range(FarthestEnemyOf(Myself),24)
    // How close is the closest ally 
    Range(NearestEnemyOf(FarthestEnemyOf(Myself)),8)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself),WIZARD_WEB)  // Cast Web on any visible enemies
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    HaveSpell(WIZARD_STINKING_CLOUD)  
    !Range(FarthestEnemyOf(Myself),20)
    !Range(NearestEnemyOf(FarthestEnemyOf(Myself)),15)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself),WIZARD_STINKING_CLOUD)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


IF
    ActionListEmpty()
    ActuallyInCombat()
    !Range(FarthestEnemyOf(Myself),18)
    Range(NearestEnemyOf(FarthestEnemyOf(Myself)),8)
    HaveSpell(WIZARD_GREASE) 
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself),WIZARD_GREASE) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    LevelGT([ENEMY],7)
    See([ENEMY])
    HPGT([ENEMY],50)
    HPPercentGT([ENEMY],80)
    !HasBounceEffects([ENEMY])
    !HasImmunityEffects([ENEMY])
    !StateCheck([ENEMY],STATE_HELPLESS)
    !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
    !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
    HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],WIZARD_HOLD_MONSTER)  // Cast Hold Monster
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    HPLT([ENEMY],90)
    See([ENEMY])
    !StateCheck([ENEMY],STATE_REALLY_DEAD)
    !StateCheck([ENEMY],STATE_NOT_TARGETABLE)
    !StateCheck([ENEMY],STATE_HARMLESS)
    !CheckStatGT([ENEMY],0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT([ENEMY],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([ENEMY],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([ENEMY],0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT([ENEMY],0,CLERIC_FREE_ACTION)
    !CheckStat([ENEMY],2,WIZARD_SPELL_IMMUNITY)
    !CheckStat([ENEMY],1,OFFENSIVE_MODIFIER)
    !CheckStat([ENEMY],1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !HasItemEquipedReal("NPSW01",[ENEMY])  // Sword of Arvoreen +2
    !HasItemEquipedReal("SW1H27",[ENEMY])  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",[ENEMY])  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",[ENEMY])  // Spider's Bane +2
    CheckStatLT([ENEMY],50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        Spell([ENEMY],WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
END
IF
    ActuallyInCombat()
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI108.SPL (Power Word: Stun)
    Range(NearestEnemyOf(Myself),30)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_POWER_WORD_STUN)  // Cast Power Word: Stun
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_SYMBOL_FEAR)  // SPWI109.SPL (Symbol of Fear)
    !CheckSpellState([ENEMY],BERSERKER_RAGE)
    !CheckSpellState([ENEMY],BARBARIAN_RAGE)
    Range(NearestEnemyOf(Myself),30)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")

    THEN
        RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_SYMBOL_FEAR)  // Cast Symbol of Fear
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_SYMBOL_STUN)  // SPWI110.SPL (Symbol of Stun)
    Range(NearestEnemyOf(Myself),30)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_SYMBOL_STUN)  // Cast Symbol of Stun
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_SYMBOL_DEATH)  // SPWI111.SPL (Symbol of Death)
    Range(NearestEnemyOf(Myself),30)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_SYMBOL_DEATH)  // Cast Symbol of Death
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI112.SPL (Power Word: Kill)
    Range(NearestEnemyOf(Myself),30)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_POWER_WORD_KILL)  // Cast Power Word: Kill
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_ENERGY_DRAIN)  // SPWI113.SPL (Energy Drain)
    Range(NearestEnemyOf(Myself),30)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_ENERGY_DRAIN)  // Cast Energy Drain
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

/*
Level: 4
Range: 40 ft.
Duration: Permanent
Casting Time: 4
Area of Effect: 1 creature
Saving Throw: Neg. 

The Polymorph Other spell is a powerful magic that permanently alters the form of 
the creature affected. Mental attributes are not affected, and the target does not 
receive the special abilities of the new form. However all physical attributes are 
changed to adhere to the new form. This is a specific version of the spell in that the
 recipient will be transformed into a squirrel unless a Save vs. Petrification/Polymorph 
 is made successfully. The transformation is instant and permanent until a Dispel Magic 
 is cast successfully upon the affected creature. The natural attacks of the new form 
 also become available and all clothes and equipment that the target was wearing will mold into the new form.
*/
IF
    ActionListEmpty()
    ActuallyInCombat()
    See([ENEMY])
    !ImmuneToSpellLevel(LastSeenBy(Myself),4)
    LevelGT(LastSeenBy(Myself),4)
    !HasBounceEffects(LastSeenBy(Myself))
    CheckStatLT(LastSeenBy(Myself),100,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),10,SAVEVSPOLY) //Atleast 50% chance 
    !Race(LastSeenBy(Myself),SWORD)
    HaveSpell(WIZARD_POLYMORPH_OTHER) 
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_POLYMORPH_OTHER)  // SPWI106.SPL (Blindness)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
    See([ENEMY])
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
    !CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    HaveSpell(WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
    See([EVILCUTOFF.HUMANOID])
    !Race(LastSeenBy(Myself),ELF)
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
    !CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
    !HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !StateCheck(Myself,STATE_SILENCED)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
    RESPONSE #100
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (Emotion: Hopelessness)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    HaveSpell(WIZARD_SPOOK)  // SPWI101.SPL (Sleep)
    !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
    !General(NearestEnemyOf(Myself),UNDEAD)  // Exclude undead
    !See(NearestEnemyOfType([ENEMY.0.GOLEM]))
    !See(NearestEnemyOfType([ENEMY.0.MEPHIT]))
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
    THEN
        RESPONSE #100
        DisplayStringHead(Myself,160)
        Spell([ENEMY],WIZARD_SPOOK)  // Cast Sleep
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

// ======================================================
// IN COMBAT SPELLCASTING - Crowd Control (CLERIC)
// ======================================================

// Cast Hold Person
// Casts Hold Person to paralyze a humanoid target, rendering them immobile and unable to act.
// Lasts for 1 turn.
IF
    ActionListEmpty()
    See([ENEMY])
    HPGT(LastSeenBy(Myself),20)
    HPPercentGT(LastSeenBy(Myself),70)
    !HasBounceEffects(LastSeenBy(Myself))
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
    !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
    General(LastSeenBy(Myself),HUMANOID)
    HaveSpell(CLERIC_HOLD_PERSON)  // SPPR012.SPL (Hold Person)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // Cast Hold Person to incapacitate the enemy
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    HPGT(NearestEnemyOf(Myself),30)
    HPPercentGT(NearestEnemyOf(Myself),90)
    !HasBounceEffects(NearestEnemyOf(Myself))
    !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
    General(NearestEnemyOf(Myself),HUMANOID)
    HaveSpell(RANGER_CHARM_ANIMAL)  // SPPR012.SPL (Hold Person)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),RANGER_CHARM_ANIMAL)  // Cast Hold Person to incapacitate the enemy
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    See([ENEMY])
    HPPercentGT(LastSeenBy(Myself),90)
    !HasBounceEffects(LastSeenBy(Myself))
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    General(LastSeenBy(Myself),HUMANOID)
    HaveSpell(CLERIC_CHARM_PERSON)  // SPPR012.SPL (Hold Person)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_CHARM_PERSON)  // Cast Hold Person to incapacitate the enemy
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    See([ENEMY])
    HPGT(LastSeenBy(Myself),20)
    LevelLT([ENEMY],6)
    !HasBounceEffects(LastSeenBy(Myself))
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    General(LastSeenBy(Myself),HUMANOID)
    HaveSpell(CLERIC_COMMAND)  // SPPR012.SPL (Hold Person)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),CLERIC_COMMAND)  // Cast Hold Person to incapacitate the enemy
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    See([ENEMY])
    General(LastSeenBy(Myself),UNDEAD)
    !HasBounceEffects(NearestEnemyOf(Myself))
    !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
    HaveSpell(LATHANDER_HOLD_UNDEAD)  // SPPR012.SPL (Hold Person)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),LATHANDER_HOLD_UNDEAD)  // Cast Hold Person to incapacitate the enemy
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(CLERIC_INSECT_PLAGUE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_INSECT_PLAGUE)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// CLERIC_SUMMON_INSECTS
IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(CLERIC_SUMMON_INSECTS)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),CLERIC_SUMMON_INSECTS)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// ======================================================
// IN COMBAT SPELLCASTING - AOE OFFENSIVE (WIZARD)
// ======================================================
/* Comet for high damage and knockback */
IF
    ActuallyInCombat()
    ActionListEmpty()
    HaveSpell(WIZARD_COMET)  // SPWI909.SPL (Comet)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself), WIZARD_COMET)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(WIZARD_DRAGONS_BREATH)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself),WIZARD_DRAGONS_BREATH)  // Cast Dragon's Breath
END

/*
Meteor Swarm
(Evocation)

Level: 9
Range: 270 ft.
Duration: 4 rounds
Casting Time: 9
Area of Effect: 15-ft. radius
Saving Throw: None

When the caster utters the words to this powerful spell, <PRO_HESHE> calls upon powerful forces indeed. 
These forces pull down meteors from above, hurling them randomly at anyone in the area of effect. 
Anyone caught in the destructive path of the meteors—whether friend or foe—will suffer 4d10 points of damage with no Saving Throw. 
The caster is well advised to be careful in <PRO_HISHER> use of this spell.
*/
IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(WIZARD_METEOR_SWARM)
    CheckStatLT(FarthestEnemyOf(Myself),100,RESISTMAGIC)
    CheckStatLT(FarthestEnemyOf(Myself),100,RESISTFIRE)
    !Range(FarthestEnemyOf(Myself),22)  
    Range(NearestEnemyOf(FarthestEnemyOf(Myself)),8)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself),WIZARD_METEOR_SWARM)  // Cast Dragon's Breath
END

/*
Death Fog
(Evocation)

Level: 6
Range: 30 ft.
Duration: 1 turn
Casting Time: 6
Area of Effect: 15-ft. radius
Saving Throw: None

The casting of a Death Fog spell creates an area of solid fog that has the additional property of being highly acidic.
All animal life not immune to acid suffers 8 points of damage for each round they are exposed to the vapors of the
Death Fog. Death Fog will also instantly kill all summoned creatures, regardless of their Hit Dice and immunities.
*/
IF
    ActionListEmpty()
    HaveSpell(WIZARD_DEATH_FOG) 
    CheckStatLT([ENEMY],100,RESISTACID)
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    !ImmuneToSpellLevel([ENEMY],1)
    !CheckSpellState([ENEMY],SI_EVOCATION)
    !Range(FarthestEnemyOf(Myself),30)  
    Range(NearestEnemyOf(FarthestEnemyOf(Myself)),8)
    NumCreatureLT([GOODCUTOFF.0.0.0.0.SUMMONED],1)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself),WIZARD_DEATH_FOG)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        Continue()
END

/*
Sphere of Chaos
(Alteration)

Level: 7
Range: 40 ft.
Duration: 1 turn
Casting Time: 7
Area of Effect: 15-ft. radius
Saving Throw: Special

All enemies within the area of effect must make a Saving Throw vs. Spell every round that they remain in the sphere. 
If the Saving Throw is failed, one of the following random effects occurs:
 – target is polymorphed into a squirrel
 – target confused
 – target bursts into flames
 – target is paralyzed
 – target is disintegrated
 – target is healed 20 Hit Points
 – target is randomly teleported
 – target is rendered unconscious
 – target is hasted
*/
IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(WIZARD_SPHERE_OF_CHAOS)
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],WIZARD_SPHERE_OF_CHAOS)  // Cast Dragon's Breath
END


IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(WIZARD_CLOUDKILL)
    CheckStatLT(FarthestEnemyOf(Myself),100,RESISTMAGIC)
    CheckStatLT(FarthestEnemyOf(Myself),100,RESISTPOISON)
    !Range(FarthestEnemyOf(Myself),16)  
    Range(NearestEnemyOf(FarthestEnemyOf(Myself)),8)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself),WIZARD_CLOUDKILL)  // Cast Dragon's Breath
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(WIZARD_INCENDIARY_CLOUD)
    CheckStatLT(FarthestEnemyOf(Myself),100,RESISTMAGIC)
    CheckStatLT(FarthestEnemyOf(Myself),100,RESISTFIRE)
    !Range(FarthestEnemyOf(Myself),16)  
    Range(NearestEnemyOf(FarthestEnemyOf(Myself)),8)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself),WIZARD_INCENDIARY_CLOUD)  // Cast Dragon's Breath
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)
    CheckStatLT(FarthestEnemyOf(Myself),100,RESISTMAGIC)
    !Range(FarthestEnemyOf(Myself),16)  
    Range(NearestEnemyOf(FarthestEnemyOf(Myself)),8)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // Cast Dragon's Breath
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(WIZARD_SKULL_TRAP)
    CheckStatLT(FarthestEnemyOf(Myself),100,RESISTMAGIC)
    !Range(FarthestEnemyOf(Myself),16)  // Ensure the enemy is within medium range
    // How close is the closest ally 
    Range(NearestEnemyOf(FarthestEnemyOf(Myself)),8)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself),WIZARD_SKULL_TRAP)  // Cast Dragon's Breath
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    OR(2)
        CheckSpellState(Myself,CHAOS_SHIELD)
        CheckSpellState(Myself,IMPROVED_CHAOS_SHIELD)
    HaveSpell(WIZARD_ALARM)  
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS") 
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_ALARM)  
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND) 
END

/* Fireball for enemies at a safe distance (30 search squares) */
IF
    ActionListEmpty()
    HaveSpell(WIZARD_FIREBALL)  // SPWI304.SPL (Fireball)
    CheckStatLT([ENEMY],100,RESISTFIRE)
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    !Range(FarthestEnemyOf(Myself),14)
    // How close is the closest ally 
    Range(NearestEnemyOf(FarthestEnemyOf(Myself)),8)
    !HasBounceEffects(FarthestEnemyOf(Myself))
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (Fireball)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

/* Ice Storm for enemies with more than 60 HP at medium range */
IF
    ActionListEmpty()
    HPGT(FarthestEnemyOf(Myself),40)
    HaveSpell(WIZARD_ICE_STORM)  // SPWI409.SPL (Ice Storm)
    CheckStatLT([ENEMY],100,RESISTCOLD)
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    !Range(FarthestEnemyOf(Myself),10)  // Ensure the enemy is within medium range
    // How close is the closest ally 
    Range(FarthestEnemyOf(FarthestEnemyOf(Myself)),8)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself),WIZARD_ICE_STORM)  // SPWI409.SPL (Ice Storm)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END



/* Burning Hands for nearby enemies with more than 20 HP */
IF
    ActionListEmpty()
    !HasBounceEffects(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
    CheckStatLT([ENEMY],100,RESISTFIRE)
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    Range(NearestEnemyOf(Myself),6)  // Ensure the enemy is close enough
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        Continue()
END

/* Color Spray for nearby enemies with more than 20 HP */
IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    NumCreatureGT([ENEMY],4)
    !HasBounceEffects(NearestEnemyOf(Myself))
    HaveSpell(WIZARD_COLOR_SPRAY)  // SPWI105.SPL (Color Spray)
    Range(NearestEnemyOf(Myself),10)  // Ensure the enemy is close enough
    !Range(NearestEnemyOf(NearestEnemyOf(Myself)),10)  // Ensure the enemy is close enough
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_COLOR_SPRAY)  // SPWI105.SPL (Color Spray)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        Continue()
END

/* Cone of Cold for a close group of enemies */
IF
    ActionListEmpty()
    HaveSpell(WIZARD_CONE_OF_COLD)  // SPWI608.SPL (Cone of Cold)
    CheckStatLT([ENEMY],100,RESISTCOLD)
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    Range(NearestEnemyOf(Myself),10)  // Ensure the enemies are close enough
    !Range(NearestEnemyOf(NearestEnemyOf(Myself)),10)  // Ensure the enemy is close enough
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(NearestEnemyOf(Myself),WIZARD_CONE_OF_COLD)  // SPWI608.SPL (Cone of Cold)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        Continue()
END

// ======================================================
// SECTION: IN COMBAT SPELLCASTING - AOE OFFENSIVE (CLERIC)
// ======================================================
IF
    ActionListEmpty()
    Range([ENEMY],25)
    !General([ENEMY],UNDEAD)  // Exclude undead
    HaveSpell(CLERIC_FALSE_DAWN)  // SPPR009.SPL (Flame Strike)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,CLERIC_FALSE_DAWN)  // Cast Flame Strike for vertical fire damage
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
        Continue()
END

IF
    ActionListEmpty()
    !Range(FarthestEnemyOf(Myself),22)
    Range(NearestEnemyOf(FarthestEnemyOf(Myself)),8)
    !HasBounceEffects(FarthestEnemyOf(Myself))
    HaveSpell(CLERIC_HOLY_SMITE)  // SPPR009.SPL (Flame Strike)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(FarthestEnemyOf(Myself),CLERIC_HOLY_SMITE)  // Cast Flame Strike for vertical fire damage
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
        Continue()
END

// ======================================================
// IN COMBAT SPELLCASTING - OFFENSIVE Single Target (WIZARD)
// ======================================================


/* 
Chromatic Orb 
(Evocation)

Level: 1
Range: 90 ft.
Duration: Special
Casting Time: 1
Area of Effect: 1 creature
Saving Throw: Special

This spell causes a 2-ft. diameter sphere to appear in the caster's hand. When thrown, the sphere heads unerringly to its target. The effect the orb has upon the target varies with the level of the caster. 
Each orb will do damage to the target against which there is no save and an effect against which the target must save vs. Spell with a +6 bonus:
 1st Level: 1d4 damage and blinds the target for 1 round.
 2nd Level: 1d4 damage and inflicts pain (-1 penalty to Strength, Dexterity, AC, and THAC0) upon the victim.
 3rd Level: 1d6 damage and burns the victim for an additional 1d8 damage.
 4th Level: 1d6 damage and blinds the target for 1 turn.
 5th Level: 1d8 damage and stuns the target for 3 rounds.
 6th Level: 1d8 damage and causes weakness (-4 penalty to THAC0) in the victim.
 7th Level: 1d10 damage and paralyzes the victim for 2 turns.
 10th Level: 1d12 acid damage and turns the victim to stone.
 12th Level: 2d8 acid damage and instantly kills the victim.

NOTE: The victim saves vs. Spell with a +6 bonus against all the effects and gets no save against the damage.
*/
IF
    ActionListEmpty()
    HaveSpell(WIZARD_CHROMATIC_ORB)  // SPWI103.SPL (Chromatic Orb)
    CheckStatLT([ENEMY],100,RESISTACID)
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    LevelGT([ENEMY],1)
    !ImmuneToSpellLevel([ENEMY],1)
    !CheckSpellState([ENEMY],SI_EVOCATION)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],WIZARD_CHROMATIC_ORB)  // SPWI103.SPL (Chromatic Orb)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
        Continue()
END

IF
    ActionListEmpty()
    OR(8)
        See([ENEMY])
        See([ENEMY.0.0.RANGER]) // Default target
        See([ENEMY.0.0.THIEF]) // Default target
        See([ENEMY.0.0.BARD_ALL]) // Default target
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.SORCERER]) // Highest priority
    HaveSpell(WIZARD_AGANNAZAR_SCORCHER) 
    !ImmuneToSpellLevel(LastSeenBy(Myself),2)
    !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
    !HasBounceEffects(LastSeenBy(Myself))
    CheckStatLT(LastSeenBy(Myself),100,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    OR(8)
        See([ENEMY])
        See([ENEMY.0.0.RANGER]) // Default target
        See([ENEMY.0.0.THIEF]) // Default target
        See([ENEMY.0.0.BARD_ALL]) // Default target
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.SORCERER]) // Highest priority
    HaveSpell(WIZARD_GHOUL_TOUCH) 
    HPGT(LastSeenBy(Myself),15)
    !HasBounceEffects(LastSeenBy(Myself))
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(Myself,WIZARD_GHOUL_TOUCH) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

/* Melf's Acid Arrow for enemies with 20-40 HP */
IF
    ActionListEmpty()
    OR(8)
        See([ENEMY])
        See([ENEMY.0.0.RANGER]) // Default target
        See([ENEMY.0.0.THIEF]) // Default target
        See([ENEMY.0.0.BARD_ALL]) // Default target
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.SORCERER]) // Highest priority
    HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI205.SPL (Melf's Acid Arrow)
    CheckStatLT([ENEMY],100,RESISTACID)
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    OR(2)
        LevelGT(LastSeenBy(Myself),2)
        GlobalTimerNotExpired("TROLL_ENEMIES","LOCALS")
    !HasBounceEffects(LastSeenBy(Myself))
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI205.SPL (Melf's Acid Arrow)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

/* Flame Arrow for enemies with 40-60 HP */
IF
    ActionListEmpty()
    HaveSpell(WIZARD_FLAME_ARROW)  // SPWI304.SPL (Flame Arrow)
    CheckStatLT([ENEMY],100,RESISTFIRE)
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    LevelGT([ENEMY],3)
    !HasBounceEffects([ENEMY])
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],WIZARD_FLAME_ARROW)  // SPWI304.SPL (Flame Arrow)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

/* Magic Missile for enemies with more than 20 HP and no bounce effects */
IF
    ActionListEmpty()
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    LevelGT([ENEMY],2)
    !HasBounceEffects([ENEMY])
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN) 
    HPPercentLT(Myself,80)
    !HasBounceEffects(NearestEnemyOf(Myself))
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],WIZARD_LARLOCH_MINOR_DRAIN) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

// ======================================================
// IN COMBAT SPELLCASTING - CURSE SINGLE TARGET (WIZARD)
// ======================================================

/*
Lower Resistance
(Abjuration)

Level: 5
Range: 40 ft.
Duration: 9 rounds + 1 round/level after 9th
Casting Time: 5
Area of Effect: 1 creature
Saving Throw: None

When cast upon a target creature, this spell will lower the Magic Resistance of this creature by 10% + 1% per level of the caster. 
There is no Saving Throw, and the target's Magic Resistance, if any, does not affect this spell. 
For example, if a creature has 60% Magic Resistance and this spell is cast on it by a 15th-level Mage, 
then the target's Magic Resistance would be lowered by 25% automatically. This effect is cumulative for 
 each casting of this spell: If Lower Resistance was cast upon the same creature again, the creature's 
 Magic Resistance would be 60% - 25% (initial casting) - 25% (current casting), which would leave the creature with 10% Magic Resistance. 
 This spell will last until its duration expires and cannot be dispelled.
*/
IF
    ActionListEmpty()
    ActuallyInCombat()
    CheckStatGT([ENEMY],50,RESISTMAGIC)
    HaveSpell(WIZARD_LOWER_RESISTANCE)  
    !ImmuneToSpellLevel([ENEMY],5)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],WIZARD_LOWER_RESISTANCE) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

/* 
Finger of Death
(Necromancy)

Level: 7
Range: Visual range of the caster 
Duration: Permanent
Casting Time: 5
Area of Effect: 1 creature
Saving Throw: Neg.

The Finger of Death spell snuffs out the victim's life force. The caster points <PRO_HISHER>
 finger at the victim after the incantation is complete, effectively ripping the life out of 
 its body unless a Save vs. Spell is made with a -2 penalty. A creature that successfully 
 saves still receives 2d8+1 points of damage.
*/
IF
    ActionListEmpty()
    HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI704.SPL (Finger of Death)
    LevelGT([ENEMY],6)
    !HasBounceEffects([ENEMY])
    !ImmuneToSpellLevel(LastSeenBy(Myself),7)
    CheckStatGT(LastSeenBy(Myself),7,SAVEVSSPELL) //50% chance that they get got
    !CheckSpellState([ENEMY],SI_NECROMANCY)
    !HasBounceEffects(LastSeenBy(Myself))
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],WIZARD_FINGER_OF_DEATH)  // SPWI704.SPL (Finger of Death)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

/* 
Power Word, Kill
(Conjuration/Summoning) 

Level: 9
Range: Visual range of the caster 
Duration: Instant
Casting Time: 1 
Area of Effect: 1 creature 
Saving Throw: None

When a Power Word, Kill spell is uttered, one creature within the spell range is slain.
The creature must have 60 or fewer current Hit Points, otherwise the spell has no effect. There is no Saving Throw.
*/
IF
    ActuallyInCombat()
    ActionListEmpty()
    CheckStatLT([ENEMY],100,RESISTFIRE)
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    !ImmuneToSpellLevel([ENEMY],9)
    !CheckSpellState([ENEMY],SI_CONJURATION)
    HPLT([ENEMY],60)
    !HasBounceEffects([ENEMY])
    HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI910.SPL (Power Word Kill)
THEN
    RESPONSE #100
        Spell([ENEMY], WIZARD_POWER_WORD_KILL)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

/*
Maze
(Conjuration/Summoning)

Level: 8
Range: Touch 
Duration: Special
Casting Time: 3
Area of Effect: 1 creature 
Saving Throw: None

An extradimensional space is brought into being upon utterance of a maze spell. 
The subject vanishes into the shifting labyrinth of force planes for a period 
of time that is totally dependent upon its Intelligence.

Intelligence of Target    —    Time trapped in maze
         under 3                —            2d4 turns
         3 to 5                   —            1d4 turns
         6 to 8                   —            5d4 rounds
         9 to 11                 —            4d4 rounds
         12 to 14               —            3d4 rounds
         15 to 17               —            2d4 rounds
         18 and up            —           1d4 rounds

Note that if the 9th-level spell Freedom is cast in the area where a creature is mazed, 
it will effectively bring <PRO_HIMHER> back to this plane, ending the spell prematurely. 
Note that a mazed creature is not freed through Dispel Magic.
*/
IF
    ActionListEmpty()
    ActuallyInCombat()
    See([ENEMY])
    LevelGT([ENEMY],6)
    !ImmuneToSpellLevel(LastSeenBy(Myself),8)
    CheckStatGT(LastSeenBy(Myself),6,SAVEVSSPELL) //and I got a reasonable chance of failing a save throw (25%+)
    !HasBounceEffects(LastSeenBy(Myself))
    HaveSpell(WIZARD_MAZE)  
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_MAZE)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

/*
Disintegrate
(Alteration)

Level: 6
Range: Visual range of the caster
Duration: Instant
Casting Time: 6
Area of Effect: 1 creature
Saving Throw: Neg.

When this spell is cast at another creature, a thin green ray is shot out. 
Upon contact with the ray, the creature must make a Saving Throw vs. Spell 
or be transformed into dust. This transformation is instantaneous and irreversible. 
There is also a good chance that this will destroy some if not all of the items that the creature is carrying.
*/
IF
    ActionListEmpty()
    HaveSpell(WIZARD_DISINTEGRATE)
    LevelGT([ENEMY],6)
    !HasBounceEffects([ENEMY])
    !ImmuneToSpellLevel([ENEMY],6)
    !CheckSpellState([ENEMY],SI_ABJURATION)
    CheckStatGT([ENEMY],10,SAVEVSSPELL) //50% chance that they get got
    !HasBounceEffects([ENEMY])
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],WIZARD_DISINTEGRATE)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See([ENEMY])
    HPPercentGT(LastSeenBy(Myself),90)
    !HasBounceEffects(LastSeenBy(Myself))
    General(LastSeenBy(Myself),HUMANOID)
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    HaveSpell(WIZARD_CHARM_PERSON) 
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_CHARM_PERSON) 
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


//Safana's charm
IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpellRES("SPIN119")  
    See([ENEMY])
    HPPercentGT(LastSeenBy(Myself),90)
    !HasBounceEffects(LastSeenBy(Myself))
    General(LastSeenBy(Myself),HUMANOID)
    !Race([ENEMY],ELF)
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
    RESPONSE #100
        SpellRES("SPIN119",LastSeenBy(Myself))  
END

/*
Blindness
(Illusion/Phantasm)

Level: 1
Range: 40 ft.
Duration: 2 hours
Casting Time: 2
Area of Effect: 1 creature
Saving Throw: Neg.

This 1st-level spell temporarily blinds its target. 
A Saving Throw is allowed and, if successful, there are no harmful effects. 
If a victim is blinded, <PRO_HESHE> receives a -4 penalty to <PRO_HISHER> attack rolls and Armor Class.
*/
IF
    ActionListEmpty()
    ActuallyInCombat()
    See([ENEMY])
    HPGT(LastSeenBy(Myself),20)
    NumCreatureLT([ENEMY],3)
    !ImmuneToSpellLevel(LastSeenBy(Myself),1)
    CheckStatGT(LastSeenBy(Myself),10,SAVEVSSPELL) //and I got a reasonable chance of failing a save throw (25%+)
    !HasBounceEffects(LastSeenBy(Myself))
    HaveSpell(WIZARD_BLINDNESS)  
    !StateCheck(LastSeenBy(Myself),STATE_BLIND)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("WIZARD_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_BLINDNESS)
        SetGlobalTimer("WIZARD_CAST","LOCALS",ONE_ROUND)
END


// ======================================================
// IN COMBAT SPELLCASTING - OFFENSIVE SINGLE TARGET (CLERIC)
// ======================================================


// Cast Flame Strike
// Casts Flame Strike to deal fire damage in a vertical column around the target.
// Lasts for 1 turn.
IF
    ActionListEmpty()
    HPGT([ENEMY],30)
    HaveSpell(CLERIC_FLAME_STRIKE)  // SPPR009.SPL (Flame Strike)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],CLERIC_FLAME_STRIKE)  // Cast Flame Strike for vertical fire damage
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    HaveSpell(BLACKGUARD_ABSORB_HEALTH)  
    OR(2)
        LevelGT([ENEMY],2)
        NumCreatureGT([ENEMY],3)
    Range([ENEMY],6)
    HPPercentLT(Myself,90)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],BLACKGUARD_ABSORB_HEALTH)  
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// Cast Harm
// Casts Harm to deal a large amount of damage to the target, reducing their HP to 1.
// Lasts for 1 turn.
IF
    ActionListEmpty()
    LevelGT([ENEMY],5)
    HaveSpell(CLERIC_HARM)  // SPPR010.SPL (Harm)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
THEN
    RESPONSE #100
        Spell([ENEMY],CLERIC_HARM)  // Cast Harm to significantly reduce enemy's HP
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// ======================================================
// SECTION: BUFFS (FIGHTER)
// ======================================================

IF
    ActionListEmpty()
    HaveSpell(WARRIOR_GREATER_WHIRLWIND)
    ActuallyInCombat()
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    Delay(30)
THEN
    RESPONSE #100
        Spell(Myself, WARRIOR_GREATER_WHIRLWIND)  // Perform Greater Whirlwind Attack
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND) 
        Continue()
END


IF
    ActionListEmpty()
    HaveSpell(WARRIOR_WHIRLWIND)
    ActuallyInCombat()
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    Delay(30)
THEN
    RESPONSE #100
        Spell(Myself, WARRIOR_GREATER_WHIRLWIND)  // Perform Greater Whirlwind Attack
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND) 
        Continue()
END


IF
    HaveSpell(WARRIOR_POWER_ATTACK)
    !CheckStat(Myself,5,DEFENSIVE_MODIFIER)
    See([ENEMY])
    !General(LastSeenBy(Myself),UNDEAD)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
    !CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
    !HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
    !HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // Sword of Arvoreen +2
    !HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        Spell(Myself,WARRIOR_POWER_ATTACK) 
        AttackReevaluate(LastSeenBy(Myself),45)
END

IF
    HaveSpell(WARRIOR_CRITICAL_STRIKE) 
    !CheckStat(Myself,3,OFFENSIVE_MODIFIER)
    Range(NearestEnemyOf(Myself),6)
THEN
    RESPONSE #100
        Spell(Myself,WARRIOR_CRITICAL_STRIKE)  
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    HaveSpell(MINSC_BERSERK)  // 3117 (MINSC_BERSERK)
    Range(NearestEnemyOf(Myself),30)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")

    THEN
        RESPONSE #100
        Spell(Myself,MINSC_BERSERK)  // Cast MINSC_BERSERK
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    HaveSpell(BERSERKER_RAGE)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(Myself,BERSERKER_RAGE)  // Cast MINSC_BERSERK
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    HaveSpell(BARBARIAN_RAGE)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(Myself,BARBARIAN_RAGE)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActuallyInCombat()
    ActionListEmpty()
    HaveSpell(KENSAI_KIA)
    Range(NearestEnemyOf(Myself),30)
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(Myself,KENSAI_KIA)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// ======================================================
// SECTION: SETTING TRAPS
// ======================================================

IF
    ActionListEmpty()
    Delay(18)
    HaveSpell(SET_SNARE_TRAP) 
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(Myself,SET_SNARE_TRAP) 
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    Delay(18)
    HaveSpell(SET_SPECIAL_SNARE_TRAP) 
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(Myself,SET_SPECIAL_SNARE_TRAP) 
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    Delay(18)
    HaveSpell(ROGUE_SET_SPIKE_TRAP) 
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(Myself,ROGUE_SET_SPIKE_TRAP) 
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    Delay(18)
    HaveSpell(ROGUE_SET_EXPLODING_TRAP)  
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(Myself,ROGUE_SET_EXPLODING_TRAP)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

IF
    ActionListEmpty()
    Delay(18)
    HaveSpell(ROGUE_SET_EXPLODING_TRAP)  
    GlobalTimerNotExpired("SHORT_BUFF","LOCALS")
    !GlobalTimerNotExpired("CLERIC_CAST","LOCALS")
    THEN
        RESPONSE #100
        Spell(Myself,ROGUE_SET_TIME_TRAP)
        SetGlobalTimer("CLERIC_CAST","LOCALS",ONE_ROUND)
END

// ======================================================
// SECTION: STEALTH AND THIEVING
// ======================================================

IF
    ActionListEmpty()
    !ActuallyInCombat()
    !StateCheck(Myself,STATE_INVISIBLE)
    !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
    OR(3)
        Class(Myself,THIEF_ALL)
        Class(Myself,RANGER_ALL)
        Class(Myself,MONK)
    !Range(NearestEnemyOf(Myself),15)
    Delay(24)
THEN
    RESPONSE #100
        Hide()  // Hide in Shadows if not in combat and no enemies nearby
        Continue()
END

IF
    ActionListEmpty()
    !ActuallyInCombat()
    OR(2)
        Class(Myself,THIEF_ALL)
        Class(Myself,MONK)
    Delay(24)
THEN
    RESPONSE #100
        FindTraps()  // Detect Traps if hidden and not in combat
        Wait(6)
        Continue()
END


IF
    Class(Myself,BARD_ALL)
    !ModalState(DETECTTRAPS)
    !StateCheck(Myself,STATE_SILENCED)
    !ModalState(BATTLESONG)
    Delay(24)
THEN
    RESPONSE #100
        BattleSong()
        Wait(18)
        Continue()
END

// ======================================================
//  TURN UNDEAD (CLERIC)
// ======================================================

IF
    General([ENEMY],UNDEAD)
    LevelGT(Myself,12)
    CanTurn([Enemy],4)
    OR(2)
        Class(Myself,PALADIN_ALL)
        Class(Myself,CLERIC_ALL)
  THEN
    RESPONSE #100
      Turn()
      Wait(12)
      Continue()
  END


// ======================================================
// SECTION: Wands
// ======================================================


IF
    HasItem("RODS06",Myself)  // Rod of Reversal
    See([ENEMY])
    OR(6)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
        CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
        CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !StateCheck(Myself,STATE_SILENCED)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
    RESPONSE #100
        DisplayStringHead(Myself,31971)  // *uses a wand*
        UseItem("RODS06",LastSeenBy(Myself))  // Rod of Reversal
END

// Wand of Frost
IF
    ActionListEmpty()
    ActuallyInCombat()
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    CheckStatLT([ENEMY],100,RESISTCOLD)
    HPGT([ENEMY],30)
    HasItemEquiped("WAND06",Myself)  
    Delay(20)
THEN
    RESPONSE #100
      UseItem("WAND06",[ENEMY]) 
END


//Wand of Fear
IF
    ActionListEmpty()
    ActuallyInCombat()
    !StateCheck([ENEMY],STATE_PANIC)
    HPGT([ENEMY],30)
    !ImmuneToSpellLevel([ENEMY],4)
    NumCreatureGT([ENEMY],2)
    HasItemEquiped("WAND02",Myself)  
    Delay(10)
THEN
    RESPONSE #100
      UseItem("WAND02",[ENEMY]) 
END

// Wand of Fireball
IF
    ActionListEmpty()
    ActuallyInCombat()
    !Range(FarthestEnemyOf(Myself),16)
    Range(NearestEnemyOf(FarthestEnemyOf(Myself)),8)
    !HasBounceEffects(FarthestEnemyOf(Myself))
    CheckStatLT(FarthestEnemyOf(Myself),100,RESISTMAGIC)
    CheckStatLT(FarthestEnemyOf(Myself),100,RESISTFIRE)
    HPGT(FarthestEnemyOf(Myself),20)
    NumCreatureGT([ENEMY],2)
    HasItemEquiped("WAND05",Myself)  
    Delay(6)
THEN
    RESPONSE #100
        UseItem("WAND05",FarthestEnemyOf(Myself)) 
END



//Wand of Paralyzation
IF
    ActionListEmpty()
    ActuallyInCombat()
    !CheckSpellState([ENEMY],HELD)
    !CheckSpellState([ENEMY],FREE_ACTION)
    !ImmuneToSpellLevel([ENEMY],4)
    HPGT([ENEMY],40)
    HasItemEquiped("WAND04",Myself)  
    Delay(20)
THEN
    RESPONSE #100
      UseItem("WAND04",[ENEMY]) 
END

//Wand of the heavens 
IF
    ActionListEmpty()
    ActuallyInCombat()
    !ImmuneToSpellLevel([ENEMY],4)
    HPGT([ENEMY],50)
    HasItemEquiped("WAND11",Myself)  
    Delay(20)
THEN
    RESPONSE #100
      UseItem("WAND11",[ENEMY]) 
END

// Wand of Magic Missile
IF
    ActionListEmpty()
    ActuallyInCombat()
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    !CheckSpellState([ENEMY],WIZARD_SHIELD)
    !HaveSpell(WIZARD_MAGIC_MISSILE)  
    !ImmuneToSpellLevel([ENEMY],4)
    LevelGT([ENEMY],2)
    HasItemEquiped("WAND03",Myself)  
THEN
    RESPONSE #100
      UseItem("WAND03",[ENEMY]) 
END


// Wand of Magic Missile
IF
    ActionListEmpty()
    ActuallyInCombat()
    CheckStatLT([ENEMY],100,RESISTMAGIC)
    !CheckSpellState([ENEMY],WIZARD_SHIELD)
    !HaveSpell(WIZARD_MAGIC_MISSILE)  
    !ImmuneToSpellLevel([ENEMY],4)
    HPGT([ENEMY],20)
    HasItemEquiped("WAND99",Myself)  
THEN
    RESPONSE #100
      UseItem("WAND99",[ENEMY]) 
END

// ======================================================
// SECTION: Combat Items (Ring of Ram, Staff of Ram Etc.)
// ======================================================



//Algernon's Cloak
IF
    ActuallyInCombat()
    ActionListEmpty()
    See([ENEMY])
    HPPercentGT(LastSeenBy(Myself),50)
    !HasBounceEffects(LastSeenBy(Myself))
    General(LastSeenBy(Myself),HUMANOID)
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)
    GlobalLT("USED_clck08","GLOBAL",1)
    HasItemEquiped("clck08",Myself)  
THEN
    RESPONSE #100
        UseItem("clck08",LastSeenBy(Myself)) 
        IncrementGlobal("USED_clck08","GLOBAL",1)
END

// Ilbratha +1
IF
    ActionListEmpty()
    ActuallyInCombat()
    !StateCheck(Myself,STATE_MIRRORIMAGE)
    GlobalLT("USED_SW1H26","GLOBAL",1)
    HasItemEquiped("SW1H26",Myself)  
THEN
    RESPONSE #100
      SetInterrupt(FALSE)
      UseItem("SW1H26",Myself) 
      SetInterrupt(TRUE)
      IncrementGlobal("USED_SW1H26","GLOBAL",1)
END

//Ring of Ram
IF
    ActionListEmpty()
    ActuallyInCombat()
    GlobalLT("USED_RING33","LOCALS",1)
    HasItemEquiped("RING33",Myself) 
THEN
    RESPONSE #100
      SetInterrupt(FALSE)
      UseItem("RING33",NearestEnemyOf(Myself)) 
      SetInterrupt(TRUE)
      IncrementGlobal("USED_RING33","LOCALS",1)
END

//The Victor
/*
Charge abilities:
– Damage: 2d6
  Range: 100 ft.
  Area of Effect: 2-ft. by 100-ft. jet
*/
IF
    ActionListEmpty()
    ActuallyInCombat()
    HPGT([ENEMY],24)
    CheckStatLT([ENEMY])
    GlobalLT("USED_RING33","LOCALS",1)
    HasItemEquiped("RING33",Myself) 
THEN
    RESPONSE #100
      SetInterrupt(FALSE)
      UseItem("RING33",[ENEMY]) 
      SetInterrupt(TRUE)
      IncrementGlobal("USED_RING33","LOCALS",1)
END


//Golden Calf Idol
IF
    ActionListEmpty()
    ActuallyInCombat()
    GlobalLT("USED_ohbrew06","LOCALS",1)
    HasItemEquiped("ohbrew06",Myself) 
THEN
    RESPONSE #100
      SetInterrupt(FALSE)
      UseItem("ohbrew06",Myself) 
      SetInterrupt(TRUE)
      IncrementGlobal("USED_ohbrew06","LOCALS",1)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    GlobalLT("USED_STAF21","LOCALS",1)
    HasItemEquiped("STAF21",Myself) 
THEN
    RESPONSE #100
      SetInterrupt(FALSE)
      UseItem("STAF21",NearestEnemyOf(Myself))  
      SetInterrupt(TRUE)
      IncrementGlobal("USED_STAF21","LOCALS",1)
END

IF
    ActionListEmpty()
    ActuallyInCombat()
    See([ENEMY])
    General(LastSeenBy(Myself),UNDEAD)
    GlobalLT("USED_SW1H31","LOCALS",1)
    HasItemEquiped("SW1H31",Myself) 
THEN
    RESPONSE #100
      SetInterrupt(FALSE)
      UseItem("SW1H31",Myself)  
      SetInterrupt(TRUE)
      IncrementGlobal("USED_SW1H31","LOCALS",1)
END

// Cast Stoneskin Gargoyle Boots
// Casts Stoneskin to grant the wizard protection from physical damage by turning their skin to stone.
// Lasts for 1 turn per caster level.
IF
    ActionListEmpty()
    GlobalLT("USED_BOOT12","LOCALS",3)
    HasItemEquiped("BOOT12",Myself) 
    CheckStatLT(Myself,1,STONESKINS)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
THEN
    RESPONSE #100
      UseItem("BOOT12",Myself)  
      IncrementGlobal("USED_BOOT12","LOCALS",1)
END

//Ethereal Boots
IF
    ActionListEmpty()
    ActuallyInCombat()
    GlobalLT("USED_BOOT11","LOCALS",1)
    HasItemEquiped("BOOT11",Myself) 
    CheckStatLT(Myself,1,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    CheckStatLT(Myself,1,DEAD_MAGIC)    
THEN
    RESPONSE #100
      SetInterrupt(FALSE)
      UseItem("BOOT11",Myself)  
      SetInterrupt(TRUE)
      IncrementGlobal("USED_BOOT11","LOCALS",1)
END

// ======================================================
// SECTION: COMBAT ACTIONS - RANGED ATTACKS
// ======================================================

//AMMO TYPE SELECTION



// Use special bow ability
IF
    ActuallyInCombat()
    ActionListEmpty()
    HaveSpell(ARCHER_CALL_SHOT) // Check if special ability is available
    OR(6)
        See([ENEMY])
        See([ENEMY.0.0.BARD_ALL]) // Default target
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.SORCERER]) // Highest priority
    !StateCheck(LastSeenBy(Myself),STATE_CHARMED)
    OR(2)
        WeaponCanDamage(LastSeenBy(Myself),BOTH)
        !IsWeaponRanged(Myself)
    !OutOfAmmo()
    CanEquipRanged()
    LevelLT(LastSeenBy(Myself),18)
    Class(Myself,RANGER)
    !Range(LastSeenBy(Myself),4)
    CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
THEN
    RESPONSE #100
        EquipRanged()  // Equip ranged weapon
        Spell(Myself,ARCHER_CALL_SHOT) // Use special bow ability
        Continue()
END
// Use special bow ability
IF
    ActuallyInCombat()
    ActionListEmpty()
    !WeaponCanDamage(LastSeenBy(Myself),BOTH)
    !IsWeaponRanged(Myself)
    !OutOfAmmo()
    CanEquipRanged()
    !Range(LastSeenBy(Myself),4)
    CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
THEN
    RESPONSE #100
        EquipRanged()  // Equip ranged weapon
        Continue()
END


IF
    ActionListEmpty()
    ActuallyInCombat()
    OR(6)
        See([ENEMY])
        See([ENEMY.0.0.BARD_ALL]) // Default target
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.SORCERER]) // Highest priority
    !StateCheck(LastSeenBy(Myself),STATE_CHARMED)
    LevelLT(LastSeenBy(Myself),21)
    OR(2)
        WeaponCanDamage(LastSeenBy(Myself),MAINHAND)
        !IsWeaponRanged(Myself)
    CanEquipRanged()
    !Range(LastSeenBy(Myself),6)  // If the enemy is within melee range (4 search squares)
    CheckStatLT(LastSeenBy(Myself),1,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // Check if Protection from Normal Missiles is already active
    CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
    !StateCheck(Myself,STATE_INVISIBLE)
    !CheckSpellState([ENEMY],PROTECTION_FROM_MAGICAL_WEAPONS)
    OR(2)
        !TookDamage()
        !Class(Myself,MAGE_ALL)
    Delay(6)
THEN
    RESPONSE #100
        EquipRanged()
        AttackReevaluate(LastSeenBy(Myself),45)
        Continue()
END

// ======================================================
// SECTION: COMBAT ACTIONS - MELEE ATTACKS
// ======================================================

IF
    ActionListEmpty()
    ActuallyInCombat()
    OR(8)
        Range([ENEMY],8)
        Class(Myself,PALADIN_ALL)
        Class(Myself,FIGHTER_ALL)
        Class(Myself,RANGER)
        Class(Myself,CLERIC_ALL)
        Class(Myself,THIEF_ALL)
        WeaponEffectiveVs([ENEMY],MAINHAND)
        WeaponCanDamage([ENEMY],MAINHAND)
     //Return true if I'm a caster but only if there's a 25% chance
    OR(8)
        See([ENEMY])
        See([ENEMY.0.0.RANGER]) // Default target
        See([ENEMY.0.0.THIEF]) // Default target
        See([ENEMY.0.0.BARD_ALL]) // Default target
        See([ENEMY.0.0.CLERIC_ALL])
        See([ENEMY.0.0.DRUID_ALL])
        See([ENEMY.0.0.MAGE_ALL])
        See([ENEMY.0.0.SORCERER]) // Highest priority
    !StateCheck(LastSeenBy(Myself),STATE_CHARMED)
    WeaponCanDamage(LastSeenBy(Myself),BOTH)
    OR(6)
        CheckStat([ENEMY],0,WEB)
        CheckStatGT(Myself,0,CLERIC_FREE_ACTION) // Check if party is being crowd-controlled
        CheckSpellState(Myself,FREE_ACTION)
        CheckStatGT(Myself,0,MINORGLOBE)
        CheckStatGT(Myself,0,SHIELDGLOBE)
        Range([ENEMY],4)
    !GlobalTimerNotExpired("USE_RANGE","LOCALS")
    HPPercentGT(Myself,35)
    OR(2)
        !TookDamage()
        !Class(Myself,MAGE_ALL)
    !CheckSpellState([ENEMY],PROTECTION_FROM_MAGICAL_WEAPONS)
    !CheckSpellState([ENEMY],RED_FIRESHIELD)
    !CheckSpellState([ENEMY],BLUE_FIRESHIELD)
    Delay(3)
THEN
    RESPONSE #100
        EquipMostDamagingMelee()  // Equip the most damaging melee weapon
        AttackReevaluate(LastSeenBy(Myself),60)
        Continue()
END

//If I'm in combat, and not near an ally go to them. Note, we can't evaluate this to attack nearest because we need to see what is nearest the player...
IF
    ActionListEmpty()
    ActuallyInCombat()
    Range([ENEMY],30)
  THEN
    RESPONSE #100
        GlobalShout(124)
END


IF
    ActionListEmpty()
    ActuallyInCombat()
    Heard([PC],ASSIST)
    HPPercentGT(Myself,35)
    !Range([ENEMY],30)
    !Range(LastHeardBy(Myself),30)
  THEN
    RESPONSE #100
        MoveToObjectOffset(LastHeardBy(Myself),[0.5])
    RESPONSE #100
        MoveToObjectOffset(LastHeardBy(Myself),[-5.0])
    RESPONSE #100
        MoveToObjectOffset(LastHeardBy(Myself),[0.-5])
    RESPONSE #100
        MoveToObjectOffset(LastHeardBy(Myself),[5.0])
END

// RESET TIMERS IF WE'RE at the bottom
IF
    ActuallyInCombat()
    Delay(20)
    True()
THEN
    RESPONSE #100
        SetGlobalTimer("WIZARD_CAST","LOCALS",0)
        SetGlobalTimer("CLERIC_CAST","LOCALS",0)
END

